"use client";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";

/* The arsenal index: 521 effects, findable, then off to their own page.
 *
 * WHY A GRID OF CARDS NOW, WHEN A ROW USED TO WIN. The row comment this replaced was right about a
 * card with no picture: 518 boxes of chrome around one word is worse than a dense table. It stopped
 * being right the day a still existed to put in the box. A poster turns the card from decoration into
 * information (SHOW, not just tell, CLAUDE.md), and search/scan works the same either way because the
 * name is still the first thing printed. `mode:"chips"` families (an easing named by its curve, a
 * blend mode defined by the CSS spec) still have nothing to show, so they keep the old pill treatment.
 *
 * WHY A LINK AND NOT A DRAWER OR AN IN-PLACE EXPANSION. Every effect now has its own URL
 * (`[stem]/page.tsx`), the same way a component library gives each component a page. A `<Link>` is
 * simpler than either alternative this file used to weigh: no open-state, no "one engine mounted"
 * bookkeeping here at all — that constraint now lives on the effect page, satisfied by construction
 * because a page can only ever show one effect.
 *
 * Filtering is client-side over an array already in the page. What is NOT in that array any more is
 * the `json` body — it moved to the effect's own (server-rendered) page, which is what actually cut
 * the first-byte payload; see effects-json.mjs's header comment.
 */

export type Entry = { name: string; stem: string; desc: string; scene: string | null; noPreview: string | null };
export type Family = {
  id: string; title: string; tag: string; intro: string;
  mode: "table" | "chips"; note: string | null; noPreview: string | null;
  count: number; undescribed: number; entries: Entry[];
};
export type Index = { total: number; previewed: number; families: number; tags: [string, number][]; list: Family[] };

// The intro strings are markdown from the doc generator: `code` and **bold** carry real meaning
// (they are the property names), so they are rendered rather than shown as punctuation.
export function Rich({ text }: { text: string }) {
  const parts = text.split(/(`[^`]+`|\*\*[^*]+\*\*)/g).filter(Boolean);
  return (
    <>
      {parts.map((p, i) =>
        p.startsWith("`") ? <code key={i}>{p.slice(1, -1)}</code>
        : p.startsWith("**") ? <b key={i}>{p.slice(2, -2)}</b>
        : <span key={i}>{p}</span>,
      )}
    </>
  );
}

// A still is only PROMISED for a previewable entry, and the promise can still miss: the sibling
// agent generating stills can fail one, or hasn't reached it yet. `broken` is the missing-still
// path; `!e.scene` (no preview at all, 294 of 521 effects) is the more common one. Both land on the
// same deliberate placeholder — a striped swatch carrying the family tag — because a blank grey box
// and a broken-image icon both read as "the site is bugged" and this is not a bug, it is a fact
// about the effect.
function Poster({ f, e }: { f: Family; e: Entry }) {
  const [broken, setBroken] = useState(false);
  const [loaded, setLoaded] = useState(false);
  const src = e.scene ? e.scene.replace(/\.json$/, ".jpg") : null;
  if (!src || broken) {
    return (
      <span className="fxcard-noimg">
        <span className="mono">{f.tag}</span>
      </span>
    );
  }
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={src}
      alt={`${e.name}, a still from its preview`}
      loading="lazy"
      width={320}
      height={180}
      // Invisible until it decodes. The still is generated by a sibling job that may not have
      // reached this effect yet, so a 404 is routine, not exceptional — and the native fallback
      // for a failed <img> is exactly the "broken image icon" the placeholder above exists to
      // avoid. Staying at opacity:0 until onLoad means that native fallback is never painted: a
      // 404 always resolves to the striped `fxcard-noimg` swatch before anything shows.
      className={loaded ? "is-loaded" : undefined}
      onLoad={() => setLoaded(true)}
      onError={() => setBroken(true)}
    />
  );
}

function Card({ f, e }: { f: Family; e: Entry }) {
  return (
    <Link href={`/showcase/effects/${e.stem}`} className="fxcard">
      <span className="fxcard-media">
        <Poster f={f} e={e} />
        {e.scene && <span className="fxdot" aria-hidden="true" title="Plays live" />}
      </span>
      <span className="fxcard-body">
        <span className="fxcard-name mono">{e.name}</span>
        {e.desc && <span className="fxcard-desc"><Rich text={e.desc} /></span>}
      </span>
    </Link>
  );
}

function Chip({ e }: { e: Entry }) {
  return (
    <Link href={`/showcase/effects/${e.stem}`} className="fxchip mono">
      {e.name}
      {e.scene && <span className="fxdot" aria-hidden="true" title="Plays live" />}
    </Link>
  );
}

/* The sticky family rail: 35 sections is too many to find by scrolling and lose again the moment you
 * scroll past the one jump list at the top. One IntersectionObserver watches every family heading;
 * whichever one last crossed the thin band just under the filter bar is "current" — the standard
 * scrollspy technique, no library. Below ~900px there is no room for a second column, so the rail
 * collapses back to the horizontal chip strip this page always had (CSS only, same DOM). */
function Rail({ families, activeId }: { families: Family[]; activeId: string | null }) {
  return (
    <nav className="fxrail" aria-label="Jump to a family">
      {families.map((f) => (
        <a key={f.id} href={`#${f.id}`} aria-current={activeId === f.id ? "location" : undefined}>
          {f.title} <span>{f.entries.length}</span>
        </a>
      ))}
    </nav>
  );
}

export function EffectsBrowser({ index }: { index: Index }) {
  const [q, setQ] = useState("");
  const [tag, setTag] = useState("");
  const [onlyPreview, setOnlyPreview] = useState(false);
  const [activeId, setActiveId] = useState<string | null>(null);
  const listRef = useRef<HTMLDivElement>(null);

  const shown = useMemo(() => {
    const needle = q.trim().toLowerCase();
    return index.list
      .filter((f) => (!tag || f.tag === tag) && (!onlyPreview || !f.noPreview))
      .map((f) => (onlyPreview ? { ...f, entries: f.entries.filter((e) => e.scene) } : f))
      .map((f) => {
        if (!needle) return f;
        // A family whose TITLE matches keeps all of its rows: typing "stings" means show me the
        // stings, not the four stings whose own names happen to contain the word.
        if (f.title.toLowerCase().includes(needle) || f.tag.includes(needle)) return f;
        const entries = f.entries.filter((e) => e.name.toLowerCase().includes(needle) || e.desc.toLowerCase().includes(needle));
        return entries.length ? { ...f, entries } : null;
      })
      .filter(Boolean) as Family[];
  }, [index.list, q, tag, onlyPreview]);

  const count = shown.reduce((n, f) => n + f.entries.length, 0);

  // Re-observe whenever the visible family set changes (a filter can remove sections mid-scroll).
  useEffect(() => {
    const root = listRef.current;
    if (!root) return;
    const sections = Array.from(root.querySelectorAll<HTMLElement>(".fxfam"));
    if (!sections.length) { setActiveId(null); return; }
    const io = new IntersectionObserver(
      (entries) => {
        for (const en of entries) if (en.isIntersecting) setActiveId(en.target.id);
      },
      // A thin band just under the sticky filter bar: a section counts as "current" the moment its
      // heading crosses into it, not whenever any sliver of it is on screen.
      { rootMargin: "-96px 0px -80% 0px", threshold: 0 },
    );
    sections.forEach((s) => io.observe(s));
    setActiveId(sections[0].id);
    return () => io.disconnect();
  }, [shown]);

  return (
    <>
      <div className="bfilter fxfilter">
        <div className="bsearch">
          <svg className="bsearch-i" viewBox="0 0 24 24" fill="none" aria-hidden="true">
            <circle cx="11" cy="11" r="7" stroke="currentColor" strokeWidth="2" />
            <path d="M20 20l-3.5-3.5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
          </svg>
          <input type="search" value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search effects, families, descriptions…" aria-label="Search effects" />
          {q && <button className="bsearch-x" onClick={() => setQ("")} aria-label="Clear search">✕</button>}
        </div>

        <div className="bselect">
          <select value={tag} onChange={(e) => setTag(e.target.value)} aria-label="Filter by tag">
            <option value="">All tags ({index.total})</option>
            {index.tags.map(([t, n]) => <option key={t} value={t}>{t} ({n})</option>)}
          </select>
          <span className="bselect-c" aria-hidden="true">▾</span>
        </div>

        <label className="fxonly">
          <input type="checkbox" checked={onlyPreview} onChange={(e) => setOnlyPreview(e.target.checked)} />
          Plays live only
        </label>

        <span className="bcount" aria-live="polite">
          {count === index.total ? `${index.total} effects` : `${count} of ${index.total}`}
        </span>
      </div>

      {shown.length === 0 && (
        <p className="bempty">
          Nothing matches <b>{q}</b>{tag && <> in <b>{tag}</b></>}.{" "}
          <button className="blink" onClick={() => { setQ(""); setTag(""); setOnlyPreview(false); }}>Clear filters</button>
        </p>
      )}

      <div className="fxlayout">
        <div className="fxrailcol">
          <Rail families={shown} activeId={activeId} />
        </div>

        <div className="fxlist" ref={listRef}>
          {shown.map((f) => (
            <section className="fxfam" id={f.id} key={f.id}>
              <h2>
                {f.title} <span className="fxn">{f.entries.length}</span>
                <span className="tag">{f.tag}</span>
                {!f.noPreview && <span className="tag fxtag-live">plays live</span>}
              </h2>
              {/* THE INTRO IS A DETAIL, NOT A HEADING. 35 families meant 35 paragraphs standing between
                  a person and the names they came to scan, and an index is for FINDING. It is still
                  here, one keystroke away, for the reader who has decided they want it. */}
              <details className="fxabout">
                <summary>What this family is for</summary>
                <p className="fxintro"><Rich text={f.intro} /></p>
              </details>
              {/* An empty description column is a gap in the registry, not a design decision. Saying
                  so is cheaper than repeating, on every card, that nobody wrote one. */}
              {f.undescribed > 0 && (
                <p className="fxgap">
                  {f.undescribed === f.count
                    ? "None of these carry a per-name description in the registry yet."
                    : `${f.undescribed} of these carry no per-name description in the registry yet.`}{" "}
                  The name and the form above are what there is.
                </p>
              )}

              {f.mode === "chips" ? (
                <>
                  {/* The catalog's own decision, quoted: these entries differ by name and nothing an
                      index can usefully picture. One paragraph, then every name. */}
                  <p className="fxskip">Near-identical across all {f.count}: {f.note}. Pick one by name.</p>
                  <div className="fxchips">{f.entries.map((e) => <Chip key={e.name} e={e} />)}</div>
                </>
              ) : (
                <div className="fxgrid">
                  {f.entries.map((e) => <Card key={e.name} f={f} e={e} />)}
                </div>
              )}
            </section>
          ))}
        </div>
      </div>
    </>
  );
}
