import data from "./easing.json";

// Generated by scripts/site/easing.mjs from core/motion. Server code only: the linear() strings make
// the file about 170 KB, so a client component gets one ease's arrays, never this module.

export type Related = { slug: string; name: string; gap: number };
export type Side = { influence: number; speed: number; name: string | null };
export type Ease = {
  slug: string;
  name: string;
  kind: "vawe" | "classic" | "css";
  family: string;
  dir: "in" | "out" | "inOut" | null;
  y: number[];
  vel: number[];
  t50: number;
  t90: number;
  at10: number;
  peakSpeed: number;
  overshoot: number;
  undershoot: number;
  linear: string;
  points: number;
  bezier: { params: number[]; exact?: boolean; worst?: number; usable?: boolean; express?: "exact" | "close" | "no" };
  blurb: string;
  use: string[];
  avoid: string[];
  related: Related[];
  nearestVawe?: Related | null;
  handles?: {
    out: Side;
    in: Side;
    shares: { outShare: number; inShare: number; pairShare: number; pairCount: number; entranceShare: number; exitShare: number; hfCount: number };
  };
  moves?: { name: string; title: string; uses: number }[];
};

export const EASES = data.eases as Ease[];
export const STATS = data.stats;
export const FAMILIES = data.families as string[];

export const easeBySlug = (slug: string) => EASES.find((e) => e.slug === slug) ?? null;
export const VAWE = EASES.filter((e) => e.kind === "vawe");
export const CSS = EASES.filter((e) => e.kind === "css");
export const classicIn = (family: string) => EASES.filter((e) => e.kind === "classic" && e.family === family);

export const PUBLISHED = "2026-10-03";

const pct = (u: number) => `${Math.round(u * 100)}%`;
const bez = (p: number[]) => `cubic-bezier(${p.join(", ")})`;
export const bezierText = (e: Ease) => bez(e.bezier.params);
export const camelOf = (slug: string) => slug.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
export const speedText = (e: Ease) => (e.peakSpeed > 20 ? "over 20x (it ends vertically)" : `${e.peakSpeed}x`);

export function pageTitle(e: Ease) {
  if (e.kind === "vawe") return `After Effects easing in CSS: ${e.slug} (speed and influence) | vawe`;
  if (e.kind === "css") return `CSS ${e.name}: cubic-bezier and linear() easing | vawe`;
  if (e.bezier.express === "no") return `${e.name}: CSS linear() easing (no cubic-bezier fit) | vawe`;
  return `${e.name}: CSS cubic-bezier and linear() easing | vawe`;
}

export function summary(e: Ease) {
  const shape = e.overshoot > 0 ? ` It passes the end value by up to ${e.overshoot}%.` : e.undershoot > 0 ? ` It dips ${e.undershoot}% below the start value first.` : "";
  return `${e.name} reaches 50% of its travel at ${pct(e.t50)} of the time and 90% at ${pct(e.t90)}. Its peak speed is ${speedText(e)} the average.${shape}`;
}

export function pageDescription(e: Ease) {
  const lead =
    e.kind === "vawe"
      ? `${e.slug}: the After Effects handles (influence and speed), the CSS linear() string, and a live demo.`
      : e.bezier.express === "no"
        ? `${e.name} as CSS: the exact linear() string, why cubic-bezier cannot draw it, and a live demo.`
        : `${e.name} as CSS: the cubic-bezier, the exact linear() string, and a live demo.`;
  const text = `${lead} 50% at ${pct(e.t50)} of the time.`;
  return text.length <= 154 ? text : lead;
}

export function waapi(e: Ease) {
  const easing = e.bezier.express === "exact" || e.kind === "css" ? bezierText(e) : e.linear;
  return `el.animate({ translate: ['0 0', '240px 0'] }, { duration: 600, easing: '${easing}', fill: 'both' });`;
}

export function importLine(e: Ease) {
  if (e.kind === "vawe") return `import { EASE } from '../../core/motion/presets.js';\n\nel.animate(\n  [{ translate: '0 4vh', opacity: 0 }, { translate: '0 0', opacity: 1 }],\n  { duration: 500, easing: EASE.${camelOf(e.slug)}, fill: 'both' },\n);\n\n// per-frame code (window.seek, vawe.onFrame): easeFn('${camelOf(e.slug)}')(u)`;
  if (e.kind === "css") return `animation: slide 600ms ${e.name};`;
  return `import { ${e.name} } from '../../core/motion/curves.js';\nimport { curveToLinear } from '../../core/motion/springs.js';\n\nconst easing = curveToLinear(${e.name}, { tolerance: 0.002 }); // the linear() string above\nconst x = ${e.name}(u);                                         // per-frame code, u in 0..1`;
}

const ORG = { "@type": "Organization", name: "Vawe", url: "https://vawe.dev" };

export function techArticleSchema(e: Ease) {
  return {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    headline: pageTitle(e).replace(/ \| vawe$/, ""),
    description: pageDescription(e),
    url: `https://vawe.dev/easing/${e.slug}`,
    inLanguage: "en",
    proficiencyLevel: "Beginner",
    datePublished: PUBLISHED,
    dateModified: PUBLISHED,
    author: ORG,
    publisher: ORG,
    about: e.kind === "vawe" ? "After Effects keyframe handles as CSS easing" : "CSS easing function",
  };
}

export function itemListSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name: "Easing functions for CSS, Web Animations and After Effects",
    numberOfItems: EASES.length,
    itemListElement: EASES.map((e, i) => ({ "@type": "ListItem", position: i + 1, name: e.name, url: `https://vawe.dev/easing/${e.slug}` })),
  };
}
