import data from "./moves.json";

// Generated by scripts/site/moves.mjs from prompts/moves. Server code only: the rendered markdown
// is about 380 KB, so a client component gets a MoveCard list, never this module's MOVES.

export type Move = {
  name: string;
  title: string;
  group: string | null;
  look: string;
  use: string;
  useWhen: string;
  jobs: string[];
  sound: string | null;
  snippet: string;
  clipHash: string | null;
  html: string;
};
export type Facet = { id: string; label: string };
export type Job = Facet & { moves: string[] };
export type MoveCard = Pick<Move, "name" | "title" | "group" | "look" | "use" | "jobs">;

export const MOVES = data.moves as Move[];
export const GROUPS = data.groups as Facet[];
export const LOOKS = data.looks as string[];
export const JOBS = data.jobs as Job[];

export const moveByName = (name: string) => MOVES.find((m) => m.name === name) ?? null;
export const groupLabel = (id: string | null) => GROUPS.find((g) => g.id === id)?.label ?? "";

export const toCard = ({ name, title, group, look, use, jobs }: Move): MoveCard => ({ name, title, group, look, use, jobs });

// mp4 and posterHd are 1280x720 for the move page; webm and poster are the 640 px grid copies.
export const clip = (name: string) => ({
  mp4: `/moves/${name}.mp4`,
  webm: `/moves/${name}.webm`,
  poster: `/moves/${name}.webp`,
  posterHd: `/moves/${name}.hd.webp`,
  md: `/moves/${name}.md`,
});
