import data from "./moves.json";

// Generated by scripts/site/moves.mjs from prompts/moves. Server code only: the rendered markdown
// is about 380 KB, so a client component gets a MoveCard list, never this module's MOVES.

export type Handle = { influence: number; speed: number };
export type Ease = { name: string; out: Handle; into: Handle };
export type Move = {
  duration: number | null;
  name: string;
  title: string;
  group: string | null;
  look: string;
  use: string;
  useWhen: string;
  jobs: string[];
  sound: string | null;
  snippet: string;
  clipHash: string | null;
  eases: Ease[];
  published: string;
  modified: string;
  clipDate: string | null;
  useHtml: string;
  codeHtml: string;
  soundHtml: string;
  notesHtml: string;
};
export type Facet = { id: string; label: string };
export type Job = Facet & { moves: string[] };
export type MoveCard = Pick<Move, "name" | "title" | "group" | "look" | "use" | "jobs" | "clipHash">;

export const MOVES = data.moves as Move[];
export const GROUPS = data.groups as Facet[];
export const LOOKS = data.looks as string[];
export const JOBS = data.jobs as Job[];

export const moveByName = (name: string) => MOVES.find((m) => m.name === name) ?? null;
export const groupLabel = (id: string | null) => GROUPS.find((g) => g.id === id)?.label ?? "";

export const toCard = ({ name, title, group, look, use, jobs, clipHash }: Move): MoveCard => ({ name, title, group, look, use, jobs, clipHash });

export { clip } from "./clip";
