// Each `html` layer's <style> block is wrapped in a prelude-less `@scope { … }` (core/type/sanitize-html.js scopeStyles), scoped to that fragment's own subtree, so the kit must be pasted VERBATIM into every fragment rather than linked; `kitCheck` below then asserts every fragment's copy is byte-identical to the one this file generates.
// The kit reads var(--accent)/var(--text)/... (set globally by applyTheme, core/engine/boot.js:279), not literal hex, because @scope walls off SELECTORS only, not inheritance, so a fragment stays correct if the theme's palette changes without a re-stamp.
export const KIT_START = '/* STAGEKIT:start (generated by `make stagekit`, DO NOT EDIT BY HAND, paste verbatim into every fragment) */';
export const KIT_END = '/* STAGEKIT:end */';

const RADIUS_BASE = { sm: 8, md: 16, lg: 28 };
const RADIUS_FACTOR_BY_ACCENT_CUT = { letterbox: 0.75, cinematicZoom: 0.9, zoom: 1.05, punch: 1.35 };
const radiusFactor = (cuts) => RADIUS_FACTOR_BY_ACCENT_CUT[cuts && cuts.accent] ?? 1;

const SPACE_STEPS = [1, 2, 3, 4, 6, 8, 12, 16]; // -> 8 16 24 32 48 64 96 128 at unit 8
const spaceUnit = (hook) => Math.min(14, Math.max(6, Math.round(hook / 11.5)));

const ELEV = {
  light: {
    1: '0 1px 1px rgba(0,0,0,.04), 0 2px 4px -2px rgba(0,0,0,.06)',
    2: '0 1px 1px -.5px rgba(0,0,0,.04), 0 3px 3px -1.5px rgba(0,0,0,.04), 0 7px 7px -3.5px rgba(0,0,0,.045), 0 16px 16px -8px rgba(0,0,0,.05)',
    3: '0 2px 2px rgba(0,0,0,.03), 0 6px 5px rgba(0,0,0,.045), 0 13px 10px rgba(0,0,0,.055), 0 22px 18px rgba(0,0,0,.07), 0 42px 34px rgba(0,0,0,.085), 0 100px 80px rgba(0,0,0,.12)',
  },
  dark: {
    1: '0 1px 2px rgba(0,0,0,.5)',
    2: '0 2px 6px rgba(0,0,0,.45), 0 8px 18px rgba(0,0,0,.4)',
    3: '0 2px 10px rgba(0,0,0,.4), 0 10px 26px rgba(0,0,0,.42), 0 28px 60px rgba(0,0,0,.48)',
  },
};
const elevFor = (light, vignette) => (light ? ELEV.light : {
  ...ELEV.dark,
  3: ELEV.dark[3].replace(/rgba\(0,0,0,\.48\)$/, `rgba(0,0,0,${(0.48 + vignette * 0.3).toFixed(2)})`),
});

/**
 * buildKit(theme) → { css, block }
 *   css:   the bare CSS rules (no <style> tag, no markers): what `make stagekit` writes to a file.
 *   block: `<style>${KIT_START}\n${css}\n${KIT_END}</style>`, the exact bytes a fragment must paste in.
 *
 * What follows is a FOUNDATION, not a reset: a type scale (already there), a spacing rhythm and an
 * optical grid (both new, both derived below), and two surface treatments (a raised `.kit-card` and a
 * quieter fill-only `.kit-panel`, so "give it a border and a shadow" stops being the only way a fragment
 * knows to separate a surface from its ground, the `Nested cards` tell `make preview` already catches).
 * Every number below traces to `resolveLook` (scale · cuts · field · layout): nothing here is a literal
 * this file chose, because 41 themes must get 41 kits, not one kit in 41 colours.
 */
export const MIN_VIDEO_TEXT_PX = 28;

function designRadiusExtras(t, radius) {
  const decls = []; const warnings = [];
  for (const [name, v] of Object.entries(t.radius || {})) {
    const num = Number(v);
    const known = name in radius;
    if (known && Math.round(radius[name]) !== Math.round(num)) {
      warnings.push(`stagekit: design.md radius.${name}=${num} shadows the kit's own radius.${name}=${radius[name]} (resolveLook has moved). Update design.md, or accept the drift.`);
    } else if (!known) decls.push(`--kit-radius-${name}:${num}px;`);
  }
  return { decls, warnings };
}

function designFlatExtras(t) {
  const decls = [];
  for (const [name, v] of Object.entries(t.shadow || {})) decls.push(`--kit-shadow-${name}:${v};`);
  for (const [name, v] of Object.entries(t.palette || {})) decls.push(`--kit-color-${name}:${String(v).toLowerCase()};`);
  for (const [name, v] of Object.entries(t.space || {})) decls.push(`--kit-space-${name}:${Number(v)}px;`);
  return decls;
}

function roleDecl(role, r) {
  const decls = [];
  if (r.size != null) decls.push(`--kit-type-${role}-size:${Number(r.size)}px;`);
  if (r.family) decls.push(`--kit-type-${role}-family:${r.family};`);
  if (r.weight != null) decls.push(`--kit-type-${role}-weight:${Number(r.weight)};`);
  if (r.tracking != null) decls.push(`--kit-type-${role}-tracking:${r.tracking}em;`);
  return decls;
}

function roleClass(role, r) {
  const family = r.family ? `var(--kit-type-${role}-family, ${r.family})` : 'var(--font-sans)';
  const size = r.size != null ? `var(--kit-type-${role}-size, ${Number(r.size)}px)` : '16px';
  const weight = r.weight != null ? `var(--kit-type-${role}-weight, ${Number(r.weight)})` : '400';
  const tracking = r.tracking != null ? `letter-spacing:var(--kit-type-${role}-tracking, ${r.tracking}em);` : '';
  return `.kit-${role}{font:${weight} ${size} ${family};${tracking}color:var(--text);margin:0}`;
}

function designTypeExtras(t, sizes) {
  const decls = []; const roleClasses = []; const warnings = [];
  for (const [role, r] of Object.entries(t.type || {})) {
    if (!r) continue;
    if (role in sizes && r.size != null && Math.round(sizes[role]) !== Math.round(Number(r.size))) {
      warnings.push(`stagekit: design.md type.${role}.size=${r.size} shadows the kit's own .kit-${role}=${sizes[role]}px (resolveLook has moved). Update design.md, or accept the drift.`);
    }
    decls.push(...roleDecl(role, r));
    roleClasses.push(roleClass(role, r));
  }
  return { decls, roleClasses, warnings };
}

function designExtras(spec, existing) {
  if (!spec) return { extraDecls: [], roleClasses: [], warnings: [] };
  const t = spec.tokens || {};
  const rad = designRadiusExtras(t, existing.radius);
  const type = designTypeExtras(t, existing.type);
  return {
    extraDecls: [...rad.decls, ...designFlatExtras(t), ...type.decls],
    roleClasses: type.roleClasses,
    warnings: [...rad.warnings, ...type.warnings],
  };
}

function applyDesignExtras(rules, spec, existing) {
  const { extraDecls, roleClasses, warnings } = designExtras(spec, existing);
  if (extraDecls.length) rules.push(`:scope{${extraDecls.join('')}}`);
  if (roleClasses.length) rules.push(...roleClasses);
  return warnings;
}

export function buildKit(theme, resolveLook, isLightBg, spec) {
  const look = resolveLook(theme, { isLightBg });
  const s = look.scale;
  const bg = theme && theme.palette && theme.palette.bg;
  const light = isLightBg && bg != null ? isLightBg(bg) : true;
  const rf = radiusFactor(look.cuts);
  const radius = { sm: Math.round(RADIUS_BASE.sm * rf), md: Math.round(RADIUS_BASE.md * rf), lg: Math.round(RADIUS_BASE.lg * rf) };
  const elev = elevFor(light, (look.field && look.field.vignette) || 0);
  const shadow = elev[2];
  const unit = spaceUnit(s.hook);
  const margin = (look.layout && look.layout.margin) || 160;
  const caption = Math.max(MIN_VIDEO_TEXT_PX, s.caption);
  const eyebrow = Math.max(MIN_VIDEO_TEXT_PX, Math.round(caption * 0.92));
  const stat = Math.round(s.hook * 1.15);
  const display = Math.round(s.hook * 2.4);

  const spaceVars = SPACE_STEPS.map((mul, i) => `--kit-space-${i + 1}:${mul * unit}px;`).join('');
  const gridCols = Array.from({ length: 12 }, (_, i) => `.kit-col-${i + 1}{grid-column:span ${i + 1}}`).join('\n');

  const rules = [
    `:scope{${spaceVars}--kit-unit:${unit}px;--kit-margin:${margin}px;--kit-gutter:var(--kit-space-4);--kit-radius-sm:${radius.sm}px;--kit-radius-md:${radius.md}px;--kit-radius-lg:${radius.lg}px}`,
    '.kit-root{position:absolute;inset:0;container-type:size;background:color-mix(in srgb, var(--line) 10%, transparent)}',
    '.kit-stage{position:absolute;left:var(--kit-margin);right:var(--kit-margin);top:0;bottom:0}',
    '.kit-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:var(--kit-gutter)}',
    gridCols,
    `.kit-card{background:var(--surface);border:1px solid var(--line);border-radius:${radius.md}px;box-shadow:${shadow}}`,
    `.kit-panel{background:var(--surface-2);border-radius:${radius.md}px}`,
    `.kit-radius-sm{border-radius:${radius.sm}px}`,
    `.kit-radius-md{border-radius:${radius.md}px}`,
    `.kit-radius-lg{border-radius:${radius.lg}px}`,
    `.kit-shadow{box-shadow:${shadow}}`,
    `:scope{--kit-elev-1:${elev[1]};--kit-elev-2:${elev[2]};--kit-elev-3:${elev[3]}}`,
    '.kit-elev-1{box-shadow:var(--kit-elev-1)}',
    '.kit-elev-2{box-shadow:var(--kit-elev-2)}',
    '.kit-elev-3{box-shadow:var(--kit-elev-3)}',
    `.kit-plane{background:var(--surface);border-radius:max(${radius.lg}px, 1.8cqw);
      box-shadow:var(--kit-elev-3), inset 0 1px 0 rgba(255,255,255,.9), 0 0 0 1px ${light ? 'rgba(15,22,32,.045)' : 'rgba(255,255,255,.06)'}}`,
    `.kit-bezel{--kit-bezel-pad:${Math.round(unit * 1.5)}px;padding:var(--kit-bezel-pad);
      background:${light ? 'rgba(15,22,32,.035)' : 'rgba(255,255,255,.05)'};
      border-radius:max(${radius.lg + Math.round(unit * 1.5)}px, 2.4cqw);
      box-shadow:0 0 0 2px ${light ? 'rgba(15,22,32,.07)' : 'rgba(255,255,255,.11)'}, var(--kit-elev-3)}`,
    `.kit-core{background:var(--surface);
      border-radius:calc(max(${radius.lg + Math.round(unit * 1.5)}px, 2.4cqw) - var(--kit-bezel-pad));
      box-shadow:inset 0 1px 0 rgba(255,255,255,.9), 0 0 0 1px ${light ? 'rgba(15,22,32,.05)' : 'rgba(255,255,255,.06)'}}`,
    `.kit-chip{display:inline-block;padding:${Math.round(unit * 0.75)}px ${Math.round(unit * 1.75)}px;
      border-radius:999px;background:var(--kit-chip-bg, var(--accent-dim));color:var(--kit-chip-fg, var(--accent));
      box-shadow:0 0 0 1px ${light ? 'rgba(37,99,235,.10)' : 'rgba(255,255,255,.08)'}}`,
    `.kit-ground-paper{background:var(--bg);--kit-chip-bg:#e6edfc;--kit-chip-fg:#1a46c0}`,
    `.kit-ground-ink{background:var(--ink);--text:#f2f5f9;--text-2:#aab6c6;--dim:#7d8b9e;
      --surface:#182231;--surface-2:#131c28;--line:#26313f;--line-strong:#33404f;
      --accent:#8fc0ff;--accent-dim:rgba(143,192,255,.16);--kit-chip-bg:#1d2a3c;--kit-chip-fg:#b4d5ff}`,
    `.kit-ground-accent{background:${(theme && theme.palette && theme.palette.accent) || '#2563eb'};--text:#ffffff;--text-2:rgba(255,255,255,.78);
      --dim:rgba(255,255,255,.62);--surface:#ffffff;--surface-2:rgba(255,255,255,.14);
      --line:rgba(255,255,255,.22);--line-strong:rgba(255,255,255,.34);
      --accent:#ffffff;--accent-dim:rgba(255,255,255,.18);--kit-chip-bg:#1e46b8;--kit-chip-fg:#ffffff}`,
    `.kit-picture{--text:${(theme.palette && theme.palette.text) || '#0f1620'};
      --text-2:${(theme.palette && theme.palette.text2) || '#454f5e'};
      --dim:${(theme.palette && theme.palette.dim) || '#697182'};
      --surface:${(theme.palette && theme.palette.surface) || '#ffffff'};
      --line:${(theme.palette && theme.palette.line) || '#e7eaf0'};
      --accent:${(theme.palette && theme.palette.accent) || '#2563eb'}}`,
    // at 1920x1080 is why a set of frames reads thin (engine-doctrine/MISTAKES.md #600).
    `.kit-grain{position:absolute;inset:0;pointer-events:none;opacity:.055;mix-blend-mode:multiply;
      background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='140' height='140'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.85' numOctaves='3'/%3E%3C/filter%3E%3Crect width='140' height='140' filter='url(%23n)'/%3E%3C/svg%3E")}`,
    '.kit-divider{height:2px;background:var(--line-strong);border:0}',
    `.kit-regmark{position:absolute;width:${Math.round(unit * 3)}px;height:${Math.round(unit * 3)}px;
      border:2px solid var(--line-strong);opacity:.55}`,
    '.kit-regmark-tl{top:var(--kit-space-5);left:var(--kit-space-5);border-right:0;border-bottom:0}',
    '.kit-regmark-tr{top:var(--kit-space-5);right:var(--kit-space-5);border-left:0;border-bottom:0}',
    '.kit-regmark-bl{bottom:var(--kit-space-5);left:var(--kit-space-5);border-right:0;border-top:0}',
    '.kit-regmark-br{bottom:var(--kit-space-5);right:var(--kit-space-5);border-left:0;border-top:0}',
    `.kit-display{font:700 ${display}px var(--font-sans);letter-spacing:-0.05em;color:var(--text);margin:0}`,
    `.kit-hook{font:700 ${s.hook}px var(--font-sans);color:var(--text);margin:0}`,
    `.kit-headline{font:700 ${s.headline}px var(--font-sans);color:var(--text);margin:0}`,
    `.kit-body{font:400 ${s.body}px var(--font-sans);color:var(--text-2);margin:0}`,
    `.kit-caption{font:400 ${caption}px var(--font-sans);color:var(--dim);margin:0}`,
    `.kit-eyebrow{font:600 ${eyebrow}px var(--font-mono);color:var(--text-2);letter-spacing:0.14em;text-transform:uppercase;margin:0}`,
    `.kit-stat{font:700 ${stat}px var(--font-num);font-variant-numeric:tabular-nums;color:var(--text);margin:0}`,
    '.kit-accent{color:var(--accent)}',
  ];

  const warnings = applyDesignExtras(rules, spec, { radius, type: { hook: s.hook, headline: s.headline, body: s.body, caption, eyebrow, stat, display } });
  return { css: rules.join('\n'), block: `<style>${KIT_START}\n${rules.join('\n')}\n${KIT_END}</style>`, look, warnings };
}

/** The token var names a fragment may use (already global, set by applyTheme, never redeclared here). */
export const KIT_TOKENS = ['--bg', '--bg-2', '--surface', '--surface-2', '--card', '--line', '--line-strong',
  '--text', '--text-2', '--dim', '--ink', '--accent', '--accent-dim', '--accent-glow', '--up', '--down',
  '--warn', '--on-accent', '--on-up', '--on-down', '--on-warn', '--font-sans', '--font-num', '--font-serif', '--font-mono'];

const KIT_BLOCK_RE = /<style[^>]*>\s*\/\*\s*STAGEKIT:start[\s\S]*?STAGEKIT:end\s*\*\/\s*<\/style>/;
export function extractKitBlock(fragmentSrc) {
  const m = KIT_BLOCK_RE.exec(String(fragmentSrc || ''));
  return m ? m[0] : null;
}

/**
 * kitCheck(goldenBlock, fragments) → { ok, findings[] }
 * fragments: [{ path, src }]. A fragment with NO kit block at all is a finding (it never opted in and
 * cannot drift, but it also cannot share the card/type-scale vocabulary, so it is worth naming). A
 * fragment whose block differs by even one byte is a finding naming the diff position.
 */
export function kitCheck(goldenBlock, fragments) {
  const findings = [];
  for (const { path: p, src } of fragments) {
    const got = extractKitBlock(src);
    if (got == null) { findings.push({ path: p, code: 'kit-missing', message: `${p}: no STAGEKIT block found. Paste the block from \`make stagekit\` verbatim at the top of the fragment.` }); continue; }
    if (got !== goldenBlock) {
      let i = 0; while (i < got.length && i < goldenBlock.length && got[i] === goldenBlock[i]) i++;
      findings.push({ path: p, code: 'kit-drift', message: `${p}: STAGEKIT block differs from the golden kit at byte ${i} (got ${JSON.stringify(got.slice(i, i + 24))}, want ${JSON.stringify(goldenBlock.slice(i, i + 24))}). Re-paste the block verbatim, do not hand-edit it.` });
    }
  }
  return { ok: findings.length === 0, findings };
}
