// quality/gates/screen-readiness.test.mjs: asserts on `readiness()` (harness/author/screen.mjs), the
// pure source-parsing half of `make screen`'s video-readiness list. No render, no browser.
//   node quality/gates/screen-readiness.test.mjs
import assert from 'node:assert/strict';
import { readiness } from '../../harness/author/screen.mjs';

const KIT = `<style>/* STAGEKIT:start (generated by \`make stagekit\`, DO NOT EDIT BY HAND, paste verbatim into every fragment) */
.kit-hook{font:700 92px var(--font-sans);color:var(--text);margin:0}
.kit-body{font:400 38px var(--font-sans);color:var(--text-2);margin:0}
.kit-eyebrow{font:600 22px var(--font-mono);color:var(--text-2);margin:0}
/* STAGEKIT:end */</style>`;

// smallest text: reads a role's size off the pasted kit block, only for roles the OWN markup uses.
{
  const r = readiness(`${KIT}<div><p class="kit-hook">Hook</p><p class="kit-body">Body</p></div>`);
  assert.equal(r.smallest, 38, 'unused kit-eyebrow (22px) must not count; smallest used role is kit-body at 38');
}
{
  const r = readiness(`${KIT}<div><p class="kit-eyebrow">Label</p></div>`);
  assert.equal(r.smallest, 22, 'a fragment that DOES use kit-eyebrow reports its real 22px');
}
{
  const r = readiness(`${KIT}<div style="font-size:44px">no role, inline only</div>`);
  assert.equal(r.smallest, 44, 'an inline font-size with no kit role is still read');
}
{
  const r = readiness(`${KIT}<div>no sized text at all</div>`);
  assert.equal(r.smallest, null, 'no text roles or inline sizes -> n/a, not 0');
}

// element count: counts tags in the fragment's OWN markup, not the pasted kit's <style> block.
{
  const r = readiness(`${KIT}<div><p class="kit-body">x</p><span>y</span></div>`);
  assert.equal(r.elementCount, 3, 'div + p + span, the <style> tag itself is not own markup after extraction');
}

// theme tokens vs raw colour.
{
  const r = readiness(`${KIT}<div style="color:var(--text);background:var(--surface)">x</div>`);
  assert.equal(r.tokenUses, 2);
  assert.equal(r.rawColorUses, 0);
}
{
  const r = readiness(`${KIT}<div style="color:#ff0000">x</div>`);
  assert.equal(r.tokenUses, 0);
  assert.equal(r.rawColorUses, 1);
}

// image paths: served, relative (the known trap), and the unfilled KIND starter marker.
{
  const r = readiness(`${KIT}<img src="/.vawe-data/uploads/vawe-flow/a.jpg">`);
  assert.equal(r.images.length, 1);
  assert.equal(r.images[0].ok, true);
  assert.equal(r.hasRealImage, true);
}
{
  const r = readiness(`${KIT}<img src="a.jpg">`);
  assert.equal(r.images[0].ok, false);
  assert.match(r.images[0].why, /relative path/);
  assert.equal(r.hasRealImage, false);
}
{
  const r = readiness(`${KIT}<img src="<fill: image path>">`);
  assert.equal(r.images[0].ok, false);
  assert.match(r.images[0].why, /unfilled/);
}

console.log('ok - screen-readiness: smallest text, element count, tokens vs raw colour, image path classification');
