// generated by harness/dev/taste-build.mjs from taste/rules: do not edit
export default {
  "speed-bands": {
    "energy_min_s": 0.15,
    "energy_max_s": 0.3,
    "professional_max_s": 0.5,
    "gravity_max_s": 0.8,
    "cinematic_max_s": 2,
    "slowest_to_fastest_min": 3,
    "eye_speed_px_per_s": 700
  },
  "stagger": {
    "gap_min_s": 0.03,
    "gap_max_s": 0.08,
    "gap_default_s": 0.05,
    "calm_min_s": 0.08,
    "calm_max_s": 0.12,
    "total_max_s": 0.5,
    "same_frame_group": 3
  },
  "exits-shorter": {
    "exit_share_min": 0.35,
    "exit_share_max": 0.6,
    "preset_leave_share": 0.6
  }
};
