// One-off generator for quality/baselines/reach.json (subtraction.plan.md Phase 1).
// Run once, output committed; not a live gate.
import fs from 'node:fs';

const R = (path, engine, author, verdict, evidence) => ({ path, engine, author, verdict, evidence });

// engine: file:line of a real consumer, or null.
// author: "storyboard verb" | "JSON (documented)" | "not at all"
// verdict: "unreachable" | "unwanted" | "unsure"
const ROWS = [
R('alongPath', 'core/fx/along-path.js:1 (registered core/fx/index.js:35)', 'JSON (documented)', 'unwanted',
  'core/fx/index.js DESCRIPTIONS gives the exact modifiers:[{alongPath:{...}}] shape; engine-doctrine/PRIMITIVES.md teaches the modifiers[] mechanism generally. Never used in 182 scenes.'),
R('amount', 'core/layers/util.js (adjust), core/motion/parts.js stagger.amount, core/fx/squash.js', 'JSON (documented)', 'unwanted',
  'Schema label documents amount per its 3 uses (adjust strength, stagger cap, squash amount). Sub-field of documented objects; simply unchosen.'),
R('anticipate', 'formats/scene/scene.js:618-624; core/timeline/clips.js:124', 'not at all', 'unreachable',
  '`make arsenal Q="anticipate"` returns "nothing matched". Not named in engine-doctrine/PRIMITIVES.md or skills/vawe-scene-authoring. Real, validated entrance-warp dial with capability nobody can find.'),
R('basis', 'core/layers/util.js:502', 'JSON (documented)', 'unwanted',
  'Schema label "Child flex-basis (px or CSS length)". Plain flex-layout knob on any group child; never set in the corpus.'),
R('blockGap', 'core/layers/doc.js:8,18', 'JSON (documented)', 'unwanted',
  'Schema-documented `doc` layer knob (default 22 used instead). The `doc` layer type itself is rare in the corpus.'),
R('blur', 'core/layers/util.js (glass path), core/layers/adjust.js (keyed pose prop)', 'JSON (documented)', 'unwanted',
  'Schema: "Gaussian blur (px) at this key. Keyable like every other pose property." A motion[]-keyable field, documented, unused.'),
R('borderTrail', 'core/layers/util.js:322-341; core/tracks/border-trail.js:1', 'JSON (documented)', 'unwanted',
  'engine-doctrine/PRIMITIVES.md:468 names "orbit (borderTrail)" directly; schema gives the full {color,width,period,arc} shape. Documented, unused.'),
R('breakAt', 'core/registry/knobs.js:98,103-105; core/surfaces/three-fx.js:31', 'JSON (documented)', 'unwanted',
  'Knob of the `three` layer\'s shatter/code* presets, which `make arsenal Q="shatter"` surfaces; schema gives its own label ("seconds before the surface breaks"). The `three` layer type ships in only 4/182 scenes, so its knobs go with it.'),
R('breakDur', 'core/registry/knobs.js:98,103-105', 'JSON (documented)', 'unwanted',
  'Same `three` shatter/code* knob family as breakAt; schema-labeled, unused because the layer type is rare, not because the knob is hidden.'),
R('breathe', 'core/lightfield: bg[].breathe path; scene.js:274-277,1294', 'JSON (documented)', 'unsure',
  'CONTRADICTS the brief\'s claim. engine-doctrine/PRIMITIVES.md:345 states it plainly: "Continuous: `bg[].breathe` (default OFF; `true` for `scale(1+0.02*sin(t/18*2pi))`, or `{amp,period}`)." That is a real recipe in the primary authoring doc, not a hidden mechanism. Marking unsure rather than overriding the prior audit outright: it is possible the audit meant something narrower (a canvas-only window, refused on `html` backgrounds per the schema label) that still counts as "no author has ever reached for it in practice." Evidence for JSON-reachability is strong; evidence for "nobody could have known" is weak. Needs a second look before either bucket is trusted.'),
R('bridge', 'core/audio/bridges.js:33-96', 'JSON (documented)', 'unwanted',
  'engine-doctrine/PRIMITIVES.md:359-367 gives the exact J-cut/L-cut JSON with `bridge`, `sound`, `lead`, `duck`, `fade`. A whole documented sound-design feature, unused in the corpus (the audio path documented in #23 as the historical example of exactly this problem).'),
R('circle', 'core/lightfield/options.js, patterns.js (field shapes); text `circle` path (rotating text) in core/type', 'JSON (documented)', 'unwanted',
  'Schema: "Lay the text CHARS on a rotating circular path (badge/seal)." Full JSON shape given. Unused.'),
R('col', 'core/engine/boot.js:52,111-115', 'JSON (documented)', 'unwanted',
  'Schema: "12-col grid placement" (a span like "2-7"). Documented grid-authoring shortcut, unused.'),
R('colGap', 'core/layers/util.js:64,485-487', 'JSON (documented)', 'unwanted', 'Schema-labeled grid-layout knob paired with the (used) `gap`; simply not reached for.'),
R('color2', 'core/layers/glow.js:172-238', 'JSON (documented)', 'unwanted',
  'Schema: required companion of a glow layer that keys the --glow-c var; the code throws a name error if missing. Documented, unused.'),
R('colw', 'core/layers/util.js:64,484', 'JSON (documented)', 'unwanted', 'Schema-labeled grid column-width knob (layout:grid). Unused.'),
R('crt', 'core/layers/util.js:355-378', 'JSON (documented)', 'unwanted',
  'engine-doctrine/PRIMITIVES.md:184 names `crt` directly in its decoration list; `make arsenal Q="crt"` finds it (5 real uses). Reachable and even lightly used, just not in the raw scene the coverage census happened to sample as "unset".'),
R('css', 'core/lightfield/index.js, core/layers/adjust.js:112', 'JSON (documented)', 'unwanted',
  'Schema: "Raw CSS the layer vocabulary does not name" - an explicit escape hatch, documented, unused.'),
R('dawnWidth', 'core/surfaces/three-fx.js:38,419', 'JSON (documented)', 'unwanted', 'Knob of the `three` globe preset; same rare-layer-type story as breakAt/breakDur.'),
R('depth', 'core/fx/plane.js (lowering target); formats/scene/scene.js:1076-1088', 'JSON (documented)', 'unwanted',
  'Schema gives far/back/front/near with exact parallax multipliers, and says explicitly it "lowers to the `plane` modifier at boot". `make arsenal Q="depth"` surfaces it with real usage descriptions. Reachable; simply the corpus has not built a scene with hand-placed parallax planes.'),
R('duck', 'core/audio/bridges.js:90-96', 'JSON (documented)', 'unwanted', 'Part of the same documented audio-bridge JSON as `bridge`/`gain`/`lead`. Unused because bridges as a whole are unused.'),
R('edgeFade', 'core/layers/image.js:9,18,38-39', 'JSON (documented)', 'unwanted', 'Schema: "Image: fade the LEFT+RIGHT edges into the bg". Plain image-layer knob, unused.'),
R('edgeFadeColor', 'core/layers/image.js:7,18,70', 'JSON (documented)', 'unwanted', 'Companion of edgeFade above; same status.'),
R('effector', 'core/tracks/effector.js:1-21; core/motion/effector.js', 'JSON (documented)', 'unwanted',
  'Schema gives the full {select,path,radius,falloff,drives,sticky,release,overshoot} shape for a travelling-point influence track. Real, documented, complex, unused - a plausible motion capability worth revisiting in Phase 6, not a candidate for deletion.'),
R('fit', 'core/layers/clip.js:6,10; core/layers/lottie.js:9,17; core/layers/text.js', 'JSON (documented)', 'unwanted', 'Shared, well-used-adjacent knob (fitH is its pair); `make arsenal Q="fit"` finds 3 real hits.'),
R('fitH', 'core/layers/text.js:13,45', 'JSON (documented)', 'unwanted', 'Schema: multi-line auto-fit height cap, paired with the (heavily used) `fit`. Simply the multi-line branch has not come up.'),
R('fov', 'core/surfaces/three-fx.js:29,932', 'JSON (documented)', 'unwanted', 'Schema: "three: camera field of view". Rare-layer-type story again.'),
R('gain', 'core/audio/bridges.js:88-96; formats/scene/scene.js:1672 (keyGain, sibling)', 'JSON (documented)', 'unwanted', 'Documented audio-bridge level knob; unused because bridges are unused.'),
R('ghost', 'core/fx/ghost.js:1; core/fx/index.js:28,35,51', 'JSON (documented)', 'unwanted',
  'core/fx/index.js\'s own DESCRIPTIONS registry calls this out as "THE FIRST EFFECT IN THIS ENGINE THAT READS TIME AS A MATERIAL" with real syntax. Documented, unused.'),
R('gridCols', 'core/layers/util.js:64,484', 'JSON (documented)', 'unwanted', 'Schema-labeled grid-layout knob. Unused.'),
R('gutter', 'core/engine/boot.js:52,111-115', 'JSON (documented)', 'unwanted', '`make arsenal Q="gutter"` finds it as part of the 12-col grid system (`col`). Unused.'),
R('hSize', 'core/layers/doc.js:8,10', 'JSON (documented)', 'unwanted', 'Schema-labeled `doc` layer knob; same rare-layer-type story as blockGap.'),
R('headColor', 'core/surfaces/paint-fx.js:35,58,135', 'JSON (documented)', 'unwanted', 'Schema: paint-matrix leading-glyph colour. Unused.'),
R('hue', 'core/lightfield/options.js (paint aurora)', 'JSON (documented)', 'unwanted', 'Schema-labeled paint-aurora knob (overrides `hues`). Unused.'),
R('hues', 'core/lightfield/options.js', 'JSON (documented)', 'unwanted', 'Companion of `hue`; same status.'),
R('in', 'core/layers/video.js:15,27-32', 'JSON (documented)', 'unwanted', 'Schema: "video: the IN point in the source, seconds." A basic, obvious video-editing field. Surprising it is unused - suggests every video layer in the corpus plays from its start.'),
R('keyClicks', 'formats/scene/scene.js:1660,1671', 'JSON (documented)', 'unwanted',
  'Real consumer (typing-layer key-click sound). engine-doctrine/MISTAKES.md #60 discusses its sibling keyGain (which the corpus DOES use), confirming the family is known and reachable, just this particular flag/cue-name pair is not.'),
R('keyCue', 'formats/scene/scene.js:1668,1671', 'JSON (documented)', 'unwanted', 'Same family as keyClicks above.'),
R('kick', 'core/fx/kick.js; core/fx/plane.js:63; core/fx/squash.js:78-83', 'JSON (documented)', 'unwanted',
  'engine-doctrine/PRIMITIVES.md:118-119 discusses "a `kick` modifier\'s `scale`" directly, and `make arsenal Q="kick"` finds it. Documented, unused.'),
R('kind', 'core/layers/adjust.js (grade kind: blur/desaturate/darken/brighten/contrast)', 'JSON (documented)', 'unwanted', 'Schema-labeled `adjust`-layer field. The `adjust` layer type itself is rarely reached for.'),
R('lag', 'core/fx/lag.js:1-50', 'JSON (documented)', 'unwanted',
  'harness/lib/contract.mjs:35-38 explicitly names `lag` as one of three mechanisms that "stay reachable the way they already are, hand-authored on a layer directly" - the contract\'s own author calls this JSON-reachable by design, not a gap.'),
R('lead', 'core/camera-moves/follow-cursor.js:15-51 (unrelated `lead`); core/audio/bridges.js (documented J-cut lead)', 'JSON (documented)', 'unwanted', 'Documented audio-bridge field (see `bridge`); unused because bridges are unused.'),
R('length', 'core/surfaces/paint-fx.js (meteor streak length)', 'JSON (documented)', 'unwanted', 'Schema-labeled paint-meteor knob. Unused.'),
R('lines', 'core/registry/knobs.js:103-105 (three code* snippet); core/layers/util.js:76-88 (crt scanline count)', 'JSON (documented)', 'unwanted', 'Two documented uses (three code-layer source, crt scanline density); both unused.'),
R('lookOpts', 'core/layers/util.js:257-269; core/looks/presets.js:16,149', 'JSON (documented)', 'unwanted',
  'Schema: "Composite-look knobs (core/looks/index.js): color / color2 / strength / grain / vignette / warmth." Directly documented override for any named `filter` look. Unused.'),
R('matte', 'core/fx/matte.js; core/layers/beam.js:91-104', 'JSON (documented)', 'unwanted',
  'core/fx/index.js DESCRIPTIONS registry and engine-doctrine/PRIMITIVES.md both describe luma-matte compositing with real syntax. Unused.'),
R('maxLines', 'core/layers/text.js:32,53; core/layers/count.js:14', 'JSON (documented)', 'unwanted', 'Schema-labeled text auto-fit safety valve. Unused.'),
R('metalness', 'core/surfaces/three-fx.js', 'JSON (documented)', 'unwanted', '`three` PBR knob; rare-layer-type story.'),
R('mixBlend', 'core/fx/mix-blend.js:42-84; core/fx/ancestor-kills.js:70', 'JSON (documented)', 'unwanted',
  'engine-doctrine/PRIMITIVES.md:451,518 gives the literal `"modifiers":[{"mixBlend":"difference"}]` example. Documented, unused.'),
R('motionPath', 'formats/scene/scene.js:496-499; core/engine/preload.js:235,275', 'not at all', 'unreachable',
  'GSAP MotionPathPlugin, auto-loaded only when the literal `motionPath` key is present in the JSON (core/engine/preload.js GSAP_PLUGINS/GSAP_TRIGGER_RE). Real, validated (core/validate/validate.mjs:825), deterministic, and per the schema label already does SUSTAINED continuous motion along an SVG path - exactly the capability the owner\'s films are measured missing (0.02 local-motion median vs 0.66 reference). `make arsenal Q="motionPath"` returns "NOTHING HERE CLEARLY MATCHES", and it is absent from engine-doctrine/PRIMITIVES.md, skills/vawe-scene-authoring, and the move:/motion: grammar (harness/lib/contract.mjs SHAPES/PART_NAMES/IDLE_NAMES). This is the plan\'s own confirmed example, and the highest-value unreachable prop in the set.'),
R('occlude', 'core/fx/occlude.js:1-19,83-112', 'JSON (documented)', 'unwanted',
  'engine-doctrine/PRIMITIVES.md:516,518 names `occlude` directly ("`occlude` and `shadow` work on one [group child]"). Documented, unused.'),
R('on', 'core/layers/glow.js (glow ring surface variant)', 'JSON (documented)', 'unwanted',
  'engine-doctrine/PRIMITIVES.md:390 gives `on:"light"` directly ("flips the ring for light surfaces"). Documented, unused.'),
R('overshoot', 'formats/scene/scene.js:618-624; core/layout/generators.js:613,652,737', 'not at all', 'unreachable',
  'Validated in the exact same code path as `anticipate` (scene.js:618-624), same "motion designers quote" phrasing, same absence from engine-doctrine/PRIMITIVES.md, skills/vawe-scene-authoring, and the move:/motion: grammar (contract.mjs). `make arsenal Q="overshoot"` only returns fuzzy word-matches on unrelated easing-curve prose, not the field itself.'),
R('ox', 'core/fx/squash.js:94,105; core/fx/lag.js:107-113', 'JSON (documented)', 'unwanted', 'Schema: keyed pivot-point X, paired with the documented `origin` static form. Unused.'),
R('oy', 'core/fx/squash.js:94,105', 'JSON (documented)', 'unwanted', 'Companion of ox above.'),
R('part', 'harness/author/capture-scene.mjs tooling', 'not at all', 'unsure',
  'Schema label is "Scene part name (capture-scene JSONs)" - this is an internal field written by the CAPTURE tooling\'s own JSON dialect, not something a film author would ever set by hand. It may not belong in the "can an author ask for this" question at all. Flagging unsure rather than assigning either delete-list bucket, since removing it could break capture-scene internals rather than removing unused authoring surface.'),
R('phaseStep', 'core/tracks/units.js:19,43; core/type/type.js:195-204', 'JSON (documented)', 'unwanted', 'Schema-labeled per-unit phase offset for looping kinetic presets (wave/shimmerWave). Unused.'),
R('physics', 'formats/scene/scene.js:505-506; core/engine/preload.js:235,275', 'not at all', 'unreachable',
  'GSAP Physics2DPlugin, auto-loaded only when the literal key is present. `make arsenal Q="physics"` returns one fuzzy hit on an unrelated easing name ("Cartoon physics"), not the mechanism itself. Absent from engine-doctrine/PRIMITIVES.md and skills/vawe-scene-authoring. This is the plan\'s own confirmed example.'),
R('plane', 'core/fx/plane.js:1-63; core/fx/index.js:25,35,58', 'JSON (documented)', 'unwanted',
  'core/fx/index.js DESCRIPTIONS and engine-doctrine/PRIMITIVES.md:328-339,458-459 both describe it with real syntax (`modifiers:[{plane:{z}}]`), and `make arsenal Q="plane"` surfaces it. Reachable; the corpus just has not built hand-placed depth planes.'),
R('poles', 'core/registry/knobs.js:99; core/surfaces/three-fx.js:33,532-542', 'JSON (documented)', 'unwanted', '`three` magnetic-preset knob (1=single source, 2=dipole). Rare-layer-type story.'),
R('poster', 'core/layers/video.js:36,49', 'JSON (documented)', 'unwanted', 'Schema: still shown before first seek resolves; schema itself notes it is "rarely visible" so the incentive to set it is genuinely low.'),
R('progress', 'core/fx/progress.js; core/fx/index.js:21,35,59', 'JSON (documented)', 'unwanted',
  'core/fx/index.js DESCRIPTIONS: "hand the layer the FILM\'s progress... as a CSS custom property". Documented, unused as an author-set field (though the underlying mechanism is exercised elsewhere).'),
R('progressiveBlur', 'core/layers/util.js:297-307,381; core/fx/matte.js:76', 'JSON (documented)', 'unwanted',
  'Schema: "Directional blur fog on the backdrop... Fades a dense grid/list into an edge." Full shape given (motion-primitives ProgressiveBlur port per project memory). Unused.'),
R('pulseAmp', 'core/layers/glow.js:170-176,318', 'JSON (documented)', 'unwanted', 'Schema-labeled glow-pulse amplitude, paired with the `pulse` preset. Unused.'),
R('rate', 'core/layers/lottie.js:21; core/layers/video.js:15,27-32; core/surfaces/paint-fx.js', 'JSON (documented)', 'unwanted', 'Schema documents two real uses (video playback rate, paint-matrix glyph rate). Unused.'),
R('rot', 'core/tracks/motion.js; core/timeline/sequence.js:169 (motion[] POSE key)', 'JSON (documented)', 'unwanted',
  'Schema: "Rotation (deg)... Keyable like every other pose property." A hand-keyed motion[] field; contract.mjs itself only reaches the SHAPES-scaled form, but hand-keying is the explicitly documented escape hatch for anything the shape vocabulary cannot express.'),
R('rotX', 'core/tracks/motion.js:167,176,188; core/timeline/sequence.js:169', 'JSON (documented)', 'unwanted', 'Documented 3D-rig rotation key, paired with the (schema-labeled) rotY and z. Needs the rig (a tilt/plane layer present) to do anything, which likely explains the zero use.'),
R('rotY', 'core/tracks/motion.js:167,176,188; core/timeline/sequence.js:169', 'JSON (documented)', 'unwanted', 'Companion of rotX above.'),
R('roughness', 'core/surfaces/three-fx.js:29,244-247,502,592', 'JSON (documented)', 'unwanted', '`three` PBR knob; rare-layer-type story.'),
R('rowGap', 'core/layers/util.js:64,486', 'JSON (documented)', 'unwanted', 'Schema-labeled grid-layout knob, paired with the used `colGap`/`gap`. Unused.'),
R('settle', 'core/surfaces/three-fx.js (deviceShowcase pose boolean)', 'JSON (documented)', 'unsure',
  'The brief lists `settle` among the confirmed-unreachable six. My own check: it IS schema-labeled with a full explanation ("three deviceShowcase: how the device is posed..."), same family as the other `three` knobs I am calling reachable-but-unwanted (breakAt, roughness, poles...). `make arsenal Q="settle"` returns only fuzzy noise (kinetic-preset prose that happens to contain the word), so the discovery-tool evidence agrees with "unreachable" while the schema-label evidence agrees with "reachable". Keeping this one unsure rather than picking a side that contradicts either the given fact or my own reading.'),
R('smoothness', 'core/layout/generators.js:660-691; core/tracks/units.js', 'JSON (documented)', 'unwanted', 'Schema-labeled range-selector smoothness dial (AE range-selector concept). Unused.'),
R('snap', 'core/beats/index.js (beatSync grid)', 'JSON (documented)', 'unwanted', 'Schema: opt a single authored time OUT of beat-sync snapping. Narrow but documented escape hatch.'),
R('sound', 'core/audio/bridges.js; core/audio/cues.js', 'JSON (documented)', 'unwanted', 'Documented bridge-texture field (see `bridge`); unused because bridges are unused.'),
R('span', 'core/audio/bridges.js:52-96', 'JSON (documented)', 'unwanted', 'Documented bridge-duration field; unused because bridges are unused.'),
R('spinDur', 'core/surfaces/three-fx.js:38,408', 'JSON (documented)', 'unwanted', '`three` globe-settle knob. Rare-layer-type story.'),
R('spinFrom', 'core/surfaces/three-fx.js:38,408', 'JSON (documented)', 'unwanted', '`three` globe rotation knob. Rare-layer-type story.'),
R('spinTo', 'core/surfaces/three-fx.js:38,408', 'JSON (documented)', 'unwanted', '`three` globe rotation knob. Rare-layer-type story.'),
R('splitText', 'formats/scene/scene.js:561-562; core/engine/preload.js:235', 'not at all', 'unreachable',
  'GSAP SplitText plugin, same auto-load-on-literal-key mechanism as motionPath/physics. `make arsenal Q="splitText"` returns nothing. The only PRIMITIVES.md hit for the string "splitText" is the UNRELATED core/type/type.js internal helper used by the (used) `split` prop, not this GSAP masked-line-reveal field - a real false-friend that would mislead an author searching the docs.'),
R('squash', 'core/fx/squash.js:1-108', 'JSON (documented)', 'unwanted',
  'core/fx/squash.js\'s own header comment gives the JSON shape (`{"squash":true}` / `{"squash":{"amount":0.22,"at":1600}}`) and core/fx/index.js DESCRIPTIONS repeats it. Documented, unused.'),
R('style', 'core/cuts/index.js PRESENTATIONS (the LOWERED cuts[].style)', 'not at all', 'unreachable',
  'AGENTS.md is explicit: "Author a boundary through transitions[] only. `cuts`... [are their] lowered internal form and the validator refuses them when written directly." The real author-facing field is `transitions[].fx` (schema.json:936), which core/transitions/lower.js converts into this `style`. No author path writes `style` directly, by design, and the validator blocks an attempt to.'),
R('sunFrom', 'core/surfaces/three-fx.js:38,416', 'JSON (documented)', 'unwanted', '`three` globe terminator knob. Rare-layer-type story.'),
R('sunLat', 'core/surfaces/three-fx.js:38,417', 'JSON (documented)', 'unwanted', '`three` globe seasonal-tilt knob. Rare-layer-type story.'),
R('sunTo', 'core/surfaces/three-fx.js:38,416', 'JSON (documented)', 'unwanted', '`three` globe terminator knob. Rare-layer-type story.'),
R('t0', 'core/layout/safe.js:392-419 (settleWindow)', 'JSON (documented)', 'unwanted', 'Schema: plain "Start (s)" field on a caption/window-like item. Basic and documented; unused in this exact spelling.'),
R('t1', 'core/layout/safe.js:392-419', 'JSON (documented)', 'unwanted', 'Companion of t0 above.'),
R('tilt', 'core/fx/tilt.js; core/fx/plane.js:2-33; core/fx/ancestor-kills.js:71', 'JSON (documented)', 'unwanted',
  'engine-doctrine/PRIMITIVES.md:328-339,458 names `tilt` directly as one of the three things that "leaves the picture plane" and builds the 3D rig, with the exact CSS longhand it owns. `make arsenal Q="tilt"` surfaces 6 real hits. Reachable and documented; the corpus just has not built a tilted-panel shot.'),
R('timeRemap', 'core/tracks/index.js:79,142; core/timeline/time.js:15-66', 'not at all', 'unreachable',
  'The plan\'s own confirmed example. `make arsenal Q="timeRemap"` returns nothing. Its sibling `timeWarp` (a simpler single-easing form of the same idea) is also unused; neither is named in engine-doctrine/PRIMITIVES.md, skills/vawe-scene-authoring, or the move:/motion: grammar (contract.mjs), which only ever scales x/y/scale/rot, never a layer\'s own clock.'),
R('upright', 'core/fx/upright.js:1-10; core/fx/index.js:32,35,61', 'JSON (documented)', 'unwanted',
  'core/fx/index.js DESCRIPTIONS gives the full rationale and JSON (`modifiers:[{"upright":"wheel"}]`); `make arsenal Q="upright"` surfaces it. Documented, unused.'),
R('voice', 'internal/audio/synth.go; core/validate/validate.mjs:1480-1494', 'JSON (documented)', 'unwanted',
  'Schema: "Synthesised voice, generated from parameters... internal/audio/synth.go owns this list." Actively validated (an audio cue must name EITHER a baked `name` OR a `voice`, never both/neither). Documented, unused - baked names are always chosen instead.'),
R('wordSlot', 'core/fx/word-slot.js:1-61', 'JSON (documented)', 'unwanted',
  'Schema gives the full {words,every,swap,chip,loop,at,delay,rise} shape with a worked example. `make arsenal Q="wordSlot"` finds it. Documented, unused.'),
R('words', 'core/type/captions.js (per-word timing override)', 'JSON (documented)', 'unwanted',
  'Schema: "Optional per-word timings [{t0,t1}]... Omit and core/type/captions.js distributes the [line] evenly." An explicit override of an already-working default, so there is a real reason nobody reaches for it: the default is good enough.'),
R('yaw', 'core/surfaces/three-fx.js (base yaw offset knob)', 'JSON (documented)', 'unwanted', '`three` surface knob shared by several presets (deviceShowcase, shatter, magnetic, codeExtrude...). Rare-layer-type story.'),
R('z', 'core/tracks/motion.js; core/timeline/sequence.js:152,169 (motion[] depth key)', 'JSON (documented)', 'unwanted',
  'Schema: "Depth (px) at this key... Animates a layer\'s DISTANCE". Documented 3D-rig motion[] key, same family as rotX/rotY. Needs the rig to do anything.'),
];

if (ROWS.length !== 94) throw new Error(`expected 94 rows, got ${ROWS.length}`);

const counts = ROWS.reduce((a, r) => { a[r.verdict] = (a[r.verdict] || 0) + 1; return a; }, {});
const out = {
  _generated_by: 'one-off, harness/dev/build-reach.mjs (see git history); not re-run automatically',
  _plan: '.claude/plans/subtraction.plan.md, Phase 1 - split the 91/94 unused schema props, delete nothing',
  _method: 'For each schema prop make coverage flags unused: (1) grep core/ and formats/scene/scene.js for a real ' +
    'consumer, opened and read, never taken on grep alone; (2) `make arsenal Q="<prop>"` as the repo\'s own single ' +
    'discovery command, checked for a real hit vs fuzzy word-noise; (3) engine-doctrine/PRIMITIVES.md and ' +
    'skills/vawe-scene-authoring/SKILL.md grepped for the prop being taught; (4) harness/author/storyboard-parse.mjs ' +
    'and harness/lib/contract.mjs read in full for a storyboard verb. unreachable = real consumer, no verb, no ' +
    'discovery-tool hit, not taught anywhere. unwanted = real consumer AND a real documented JSON path (schema ' +
    'label plus PRIMITIVES.md/arsenal/fx-registry backing), simply never chosen in the library. unsure = evidence ' +
    'conflicts or the prop is not really an authoring surface at all.',
  counts,
  props: ROWS,
};
fs.writeFileSync(new URL('../../quality/baselines/reach.json', import.meta.url), JSON.stringify(out, null, 2) + '\n');
console.log(counts);
