// stagekit.mjs: THE STAGE KIT. A small CSS block, derived from a theme's own resolveLook(), that every
// per-scene HTML fragment in a fan-out carries VERBATIM.
//
// WHY VERBATIM AND NOT A LINKED STYLESHEET. Each `html` layer's <style> block is wrapped in a
// prelude-less `@scope { … }` (core/type/sanitize-html.js scopeStyles), scoped to that fragment's own
// subtree. A shared stylesheet cannot reach across fragments, so the only way for three scene agents to
// draw the same card, the same radius, the same type scale is to give each of them the identical bytes
// and let each paste them in. That is what makes the kit CHECKABLE: `kitCheck` below asserts every
// fragment's copy is byte-identical to the one this file generates, so drift between three agents'
// fragments is impossible rather than merely discouraged.
//
// The kit reads var(--accent)/var(--text)/... (set globally by applyTheme, core/engine/boot.js:279),
// NOT literal hex: those custom properties are declared on :root, which @scope does not wall off (only
// SELECTORS are scoped, inheritance is not), so a fragment stays correct if the theme's palette changes
// without a re-stamp. Only the SIZES (type scale, radius, shadow) are theme-specific numbers, because
// those come from `resolveLook`, which has no CSS-variable form.
export const KIT_START = '/* STAGEKIT:start (generated by `make stagekit`, DO NOT EDIT BY HAND, paste verbatim into every fragment) */';
export const KIT_END = '/* STAGEKIT:end */';

// RADIUS_BASE is the reference tier (vawe's own hand-authored corners, bounce 0.08, cuts.accent
// "cinematicZoom"), not a constant every theme gets: `radiusFactor` below scales it by how much
// overshoot the theme's own ACCENT cut carries (theme-contract.js CUT_ACCENT_TIERS), so a near-still
// brand (letterbox, punch-free) reads more rectilinear and a bouncy one (punch) reads rounder, the same
// direction Swiss-system practice argues (near-zero radius on a restrained brand) without a second,
// disagreeing formula: it is the SAME accent-cut name the film's own transitions already resolve to.
const RADIUS_BASE = { sm: 8, md: 16, lg: 28 };
const RADIUS_FACTOR_BY_ACCENT_CUT = { letterbox: 0.75, cinematicZoom: 0.9, zoom: 1.05, punch: 1.35 };
const radiusFactor = (cuts) => RADIUS_FACTOR_BY_ACCENT_CUT[cuts && cuts.accent] ?? 1;

// The spacing atom is NOT a literal 8px: it is the theme's own hook size (already derived from
// `motion.enter`, theme-contract.js scaleFromMotion) divided back down to a baseline-grid unit. Picked
// so the reference brand (vawe, hook 92) lands on exactly LAYOUT.md's own house ladder (8 16 24 32 48 64
// 96 128, the §3 "space on a scale" rule), so every other theme gets a proportional VARIANT of that same
// law rather than a second, disagreeing one: a theme with a bigger hook (a louder, more cinematic brand)
// gets a roomier rhythm; a quieter one gets a tighter one. Clamped so an extreme hook cannot collapse or
// blow out the ladder.
const SPACE_STEPS = [1, 2, 3, 4, 6, 8, 12, 16]; // -> 8 16 24 32 48 64 96 128 at unit 8
const spaceUnit = (hook) => Math.min(14, Math.max(6, Math.round(hook / 11.5)));

// Shadow reads light-vs-dark off the SAME isLightBg the rest of the theme contract uses (never a second
// heuristic), because a single 35%-black blob is right for almost no light theme (it reads muddy, the
// generic-AI-card tell) and under-commits on most dark ones. `field.vignette` (already computed from
// light/dark, theme-contract.js DEFAULT_FIELD_LIGHT/DARK) scales the dark tier's depth: a theme with a
// deeper vignette gets a deeper card shadow, so the card and its own backdrop agree on how dramatic the
// brand is instead of the card carrying a flat default no theme chose.
const shadowFor = (light, vignette) => (light
  ? '0 1px 2px rgba(15,18,15,.06), 0 14px 34px rgba(15,18,15,.10)'
  : `0 2px 10px rgba(0,0,0,.4), 0 18px 44px rgba(0,0,0,${(0.32 + vignette * 0.7).toFixed(2)})`);

/**
 * buildKit(theme) → { css, block }
 *   css:   the bare CSS rules (no <style> tag, no markers): what `make stagekit` writes to a file.
 *   block: `<style>${KIT_START}\n${css}\n${KIT_END}</style>`, the exact bytes a fragment must paste in.
 *
 * What follows is a FOUNDATION, not a reset: a type scale (already there), a spacing rhythm and an
 * optical grid (both new, both derived below), and two surface treatments (a raised `.kit-card` and a
 * quieter fill-only `.kit-panel`, so "give it a border and a shadow" stops being the only way a fragment
 * knows to separate a surface from its ground, the `Nested cards` tell `make preview` already catches).
 * Every number below traces to `resolveLook` (scale · cuts · field · layout): nothing here is a literal
 * this file chose, because 41 themes must get 41 kits, not one kit in 41 colours.
 */
export function buildKit(theme, resolveLook, isLightBg) {
  const look = resolveLook(theme, { isLightBg });
  const s = look.scale;
  const bg = theme && theme.palette && theme.palette.bg;
  const light = isLightBg && bg != null ? isLightBg(bg) : true;
  const rf = radiusFactor(look.cuts);
  const radius = { sm: Math.round(RADIUS_BASE.sm * rf), md: Math.round(RADIUS_BASE.md * rf), lg: Math.round(RADIUS_BASE.lg * rf) };
  const shadow = shadowFor(light, (look.field && look.field.vignette) || 0);
  const unit = spaceUnit(s.hook);
  const margin = (look.layout && look.layout.margin) || 160;
  const eyebrow = Math.max(14, Math.round(s.caption * 0.92));
  const stat = Math.round(s.hook * 1.15);

  const spaceVars = SPACE_STEPS.map((mul, i) => `--kit-space-${i + 1}:${mul * unit}px;`).join('');
  const gridCols = Array.from({ length: 12 }, (_, i) => `.kit-col-${i + 1}{grid-column:span ${i + 1}}`).join('\n');

  const css = [
    // --- tokens: spacing rhythm, the content column, the grid gutter. `:scope` is the fragment's own
    // root element (the prelude-less `@scope` block's implicit root, sanitize-html.js scopeStyles), so
    // these reach every element in the fragment without depending on which class sits where.
    `:scope{${spaceVars}--kit-unit:${unit}px;--kit-margin:${margin}px;--kit-gutter:var(--kit-space-4)}`,
    // --- ground: a full-bleed root needs a ground of its own, or `audit` reads it as one giant text box.
    // 10%, not a rounder number: `--line` is sometimes already translucent (rgba, most dark themes) and
    // sometimes fully opaque (a brand that authors it as a flat hex, e.g. plinth), so the SAME percentage
    // reads as a bare hint on one theme and a visible wash across the whole frame on the other. 10% keeps
    // the wash under the "near-invisible" bar this constraint asks for even against an opaque `--line`.
    '.kit-root{position:absolute;inset:0;container-type:size;background:color-mix(in srgb, var(--line) 10%, transparent)}',
    // --- the content column and a 12-col grid for asymmetric splits (col:"2-7" style, by hand) --------
    '.kit-stage{position:absolute;left:var(--kit-margin);right:var(--kit-margin);top:0;bottom:0}',
    '.kit-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:var(--kit-gutter)}',
    gridCols,
    // --- surfaces: a RAISED card (border + shadow) and a QUIET panel (fill only, no border/shadow) ----
    // Reach for `.kit-panel` when the surface needs to read as PART of the ground (a grouped region, a
    // dense instrument face); reach for `.kit-card` only when it needs to read as ON TOP of it (one
    // floating object). Giving every surface a border is the `Nested cards` tell the detector catches.
    `.kit-card{background:var(--surface);border:1px solid var(--line);border-radius:${radius.md}px;box-shadow:${shadow}}`,
    `.kit-panel{background:var(--surface-2);border-radius:${radius.md}px}`,
    `.kit-radius-sm{border-radius:${radius.sm}px}`,
    `.kit-radius-md{border-radius:${radius.md}px}`,
    `.kit-radius-lg{border-radius:${radius.lg}px}`,
    `.kit-shadow{box-shadow:${shadow}}`,
    // --- a hairline divider: the structural rule LAYOUT.md §0 asks for, distinct from a card's border --
    '.kit-divider{height:1px;background:var(--line);border:0}',
    // --- type scale (unchanged shape) plus an eyebrow/kicker and a tabular stat number ----------------
    `.kit-hook{font:700 ${s.hook}px var(--font-sans);color:var(--text);margin:0}`,
    `.kit-headline{font:700 ${s.headline}px var(--font-sans);color:var(--text);margin:0}`,
    `.kit-body{font:400 ${s.body}px var(--font-sans);color:var(--text-2);margin:0}`,
    `.kit-caption{font:400 ${s.caption}px var(--font-sans);color:var(--dim);margin:0}`,
    `.kit-eyebrow{font:600 ${eyebrow}px var(--font-mono);color:var(--text-2);letter-spacing:0.14em;text-transform:uppercase;margin:0}`,
    `.kit-stat{font:700 ${stat}px var(--font-num);font-variant-numeric:tabular-nums;color:var(--text);margin:0}`,
    '.kit-accent{color:var(--accent)}',
  ].join('\n');
  const block = `<style>${KIT_START}\n${css}\n${KIT_END}</style>`;
  return { css, block, look };
}

/** The token var names a fragment may use (already global, set by applyTheme, never redeclared here). */
export const KIT_TOKENS = ['--bg', '--bg-2', '--surface', '--surface-2', '--card', '--line', '--line-strong',
  '--text', '--text-2', '--dim', '--ink', '--accent', '--accent-dim', '--accent-glow', '--up', '--down',
  '--warn', '--on-accent', '--on-up', '--on-down', '--on-warn', '--font-sans', '--font-num', '--font-serif', '--font-mono'];

// extractKitBlock(fragmentSrc) → the bytes between KIT_START/KIT_END, INCLUDING the markers and the
// enclosing <style> tag, or null if the fragment carries no kit block at all. Comments are stripped
// first (core/type/sanitize-html.js stripComments) so a fragment's own prose about "the kit" cannot be
// mistaken for the marker; the renderer strips them the same way before any regex ever sees the markup.
const KIT_BLOCK_RE = /<style[^>]*>\s*\/\*\s*STAGEKIT:start[\s\S]*?STAGEKIT:end\s*\*\/\s*<\/style>/;
export function extractKitBlock(fragmentSrc) {
  const m = KIT_BLOCK_RE.exec(String(fragmentSrc || ''));
  return m ? m[0] : null;
}

/**
 * kitCheck(goldenBlock, fragments) → { ok, findings[] }
 * fragments: [{ path, src }]. A fragment with NO kit block at all is a finding (it never opted in and
 * cannot drift, but it also cannot share the card/type-scale vocabulary, so it is worth naming). A
 * fragment whose block differs by even one byte is a finding naming the diff position.
 */
export function kitCheck(goldenBlock, fragments) {
  const findings = [];
  for (const { path: p, src } of fragments) {
    const got = extractKitBlock(src);
    if (got == null) { findings.push({ path: p, code: 'kit-missing', message: `${p}: no STAGEKIT block found. Paste the block from \`make stagekit\` verbatim at the top of the fragment.` }); continue; }
    if (got !== goldenBlock) {
      let i = 0; while (i < got.length && i < goldenBlock.length && got[i] === goldenBlock[i]) i++;
      findings.push({ path: p, code: 'kit-drift', message: `${p}: STAGEKIT block differs from the golden kit at byte ${i} (got ${JSON.stringify(got.slice(i, i + 24))}, want ${JSON.stringify(goldenBlock.slice(i, i + 24))}). Re-paste the block verbatim, do not hand-edit it.` });
    }
  }
  return { ok: findings.length === 0, findings };
}
