// stagekit.mjs: THE STAGE KIT. A small CSS block, derived from a theme's own resolveLook(), that every
// per-scene HTML fragment in a fan-out carries VERBATIM.
//
// WHY VERBATIM AND NOT A LINKED STYLESHEET. Each `html` layer's <style> block is wrapped in a
// prelude-less `@scope { … }` (core/type/sanitize-html.js scopeStyles), scoped to that fragment's own
// subtree. A shared stylesheet cannot reach across fragments, so the only way for three scene agents to
// draw the same card, the same radius, the same type scale is to give each of them the identical bytes
// and let each paste them in. That is what makes the kit CHECKABLE: `kitCheck` below asserts every
// fragment's copy is byte-identical to the one this file generates, so drift between three agents'
// fragments is impossible rather than merely discouraged.
//
// The kit reads var(--accent)/var(--text)/... (set globally by applyTheme, core/engine/boot.js:279),
// NOT literal hex: those custom properties are declared on :root, which @scope does not wall off (only
// SELECTORS are scoped, inheritance is not), so a fragment stays correct if the theme's palette changes
// without a re-stamp. Only the SIZES (type scale, radius, shadow) are theme-specific numbers, because
// those come from `resolveLook`, which has no CSS-variable form.
export const KIT_START = '/* STAGEKIT:start (generated by `make stagekit`, DO NOT EDIT BY HAND, paste verbatim into every fragment) */';
export const KIT_END = '/* STAGEKIT:end */';

const RADIUS = { sm: 8, md: 16, lg: 28 };

/**
 * buildKit(theme) → { css, block }
 *   css:   the bare CSS rules (no <style> tag, no markers): what `make stagekit` writes to a file.
 *   block: `<style>${KIT_START}\n${css}\n${KIT_END}</style>`, the exact bytes a fragment must paste in.
 */
export function buildKit(theme, resolveLook, isLightBg) {
  const look = resolveLook(theme, { isLightBg });
  const s = look.scale;
  const css = [
    '.kit-card{background:var(--surface);border:1px solid var(--line);border-radius:' + RADIUS.md + 'px;box-shadow:0 8px 30px rgba(0,0,0,.35)}',
    '.kit-radius-sm{border-radius:' + RADIUS.sm + 'px}',
    '.kit-radius-md{border-radius:' + RADIUS.md + 'px}',
    '.kit-radius-lg{border-radius:' + RADIUS.lg + 'px}',
    '.kit-shadow{box-shadow:0 8px 30px rgba(0,0,0,.35)}',
    `.kit-hook{font:700 ${s.hook}px var(--font-sans);color:var(--text);margin:0}`,
    `.kit-headline{font:700 ${s.headline}px var(--font-sans);color:var(--text);margin:0}`,
    `.kit-body{font:400 ${s.body}px var(--font-sans);color:var(--text-2);margin:0}`,
    `.kit-caption{font:400 ${s.caption}px var(--font-sans);color:var(--dim);margin:0}`,
    '.kit-accent{color:var(--accent)}',
  ].join('\n');
  const block = `<style>${KIT_START}\n${css}\n${KIT_END}</style>`;
  return { css, block, look };
}

/** The token var names a fragment may use (already global, set by applyTheme, never redeclared here). */
export const KIT_TOKENS = ['--bg', '--bg-2', '--surface', '--surface-2', '--card', '--line', '--line-strong',
  '--text', '--text-2', '--dim', '--ink', '--accent', '--accent-dim', '--accent-glow', '--up', '--down',
  '--warn', '--on-accent', '--on-up', '--on-down', '--on-warn', '--font-sans', '--font-num', '--font-serif', '--font-mono'];

// extractKitBlock(fragmentSrc) → the bytes between KIT_START/KIT_END, INCLUDING the markers and the
// enclosing <style> tag, or null if the fragment carries no kit block at all. Comments are stripped
// first (core/type/sanitize-html.js stripComments) so a fragment's own prose about "the kit" cannot be
// mistaken for the marker; the renderer strips them the same way before any regex ever sees the markup.
const KIT_BLOCK_RE = /<style[^>]*>\s*\/\*\s*STAGEKIT:start[\s\S]*?STAGEKIT:end\s*\*\/\s*<\/style>/;
export function extractKitBlock(fragmentSrc) {
  const m = KIT_BLOCK_RE.exec(String(fragmentSrc || ''));
  return m ? m[0] : null;
}

/**
 * kitCheck(goldenBlock, fragments) → { ok, findings[] }
 * fragments: [{ path, src }]. A fragment with NO kit block at all is a finding (it never opted in and
 * cannot drift, but it also cannot share the card/type-scale vocabulary, so it is worth naming). A
 * fragment whose block differs by even one byte is a finding naming the diff position.
 */
export function kitCheck(goldenBlock, fragments) {
  const findings = [];
  for (const { path: p, src } of fragments) {
    const got = extractKitBlock(src);
    if (got == null) { findings.push({ path: p, code: 'kit-missing', message: `${p}: no STAGEKIT block found. Paste the block from \`make stagekit\` verbatim at the top of the fragment.` }); continue; }
    if (got !== goldenBlock) {
      let i = 0; while (i < got.length && i < goldenBlock.length && got[i] === goldenBlock[i]) i++;
      findings.push({ path: p, code: 'kit-drift', message: `${p}: STAGEKIT block differs from the golden kit at byte ${i} (got ${JSON.stringify(got.slice(i, i + 24))}, want ${JSON.stringify(goldenBlock.slice(i, i + 24))}). Re-paste the block verbatim, do not hand-edit it.` });
    }
  }
  return { ok: findings.length === 0, findings };
}
