export const PROFILES = {
  linear: {
    cuts: ['none', 'blur'], stings: [], bounceOk: false, restraint: 'high',
    banCuts: ['whip', 'wipe', 'spin', 'cube', 'roll'], face: 'mono',
    pace: 'fast, snappy', easing: 'easeOutQuart', dominance: 'dark', accent: 'one cool (cobalt/indigo)',
    look: 'none, or one crt/matrixDecode backdrop at low intensity',
    blurb: 'technical, dark, restrained. Dev tools. Restraint IS the personality',
    antiBlurb: 'dense terminal readouts and hard cuts, with almost no effects',
  },
  apple: {
    cuts: ['fade', 'riseBlur'], stings: ['lens'], bounceOk: false, restraint: 'high',
    banCuts: ['whip', 'wipe', 'punch', 'jitter'], face: 'sans',
    pace: 'slow and smooth, 0.5-0.9s', easing: 'easeOutCubic', dominance: 'light or deep black',
    accent: 'one, often none', look: 'almost absent. A single lens/chrome glamour moment',
    blurb: 'premium, calm, generous. A product launch. Dissolves, never whips',
    antiBlurb: 'slow, reverent, held frames with huge whitespace',
  },
  stripe: {
    cuts: ['blur', 'fade'], stings: ['dissolve'], bounceOk: false, restraint: 'med',
    banCuts: ['whip', 'jitter'], face: 'sans',
    pace: 'smooth, confident', easing: 'easeOutCubic', dominance: 'light',
    accent: 'gradient (cobalt to violet)', look: 'a soft flow/aurora field behind',
    blurb: 'clean-tech, warm-serious. A developer brand. Trust plus a little warmth',
    antiBlurb: 'soft gradient fields and humanist type, warm but serious',
  },
  nike: {
    cuts: ['whip', 'punch'], stings: ['flash', 'streak'], bounceOk: 'accent', restraint: 'low',
    banCuts: [], face: 'sans',
    pace: 'punchy, nothing sits still', easing: 'easeOutExpo', dominance: 'bold full-bleed',
    accent: 'one loud, on black or white', look: 'motion blur ON, kinetic type is the star',
    blurb: 'energetic, kinetic, high-contrast. A sports ad. Motion drives everything',
    antiBlurb: 'loud, fast, high-contrast, with the type doing the shouting',
  },
  a24: {
    cuts: ['fade', 'letterbox'], stings: ['ink', 'leak'], bounceOk: false, restraint: 'high',
    banCuts: ['whip', 'wipe', 'spin'], banMotion: ['pop'], face: 'serif',
    pace: 'slow, deliberate, long holds', easing: 'easeOutExpo', dominance: 'dark, letterboxed',
    accent: 'one muted', look: 'grain throughout, one vortex at the turn',
    blurb: 'dramatic, editorial, tense. A film trailer. Silence and stillness are the tension',
    antiBlurb: 'moody, letterboxed, grainy film-trailer tension',
  },
  bloomberg: {
    cuts: ['collapse', 'punch'], stings: ['scan'], bounceOk: false, restraint: 'med',
    banCuts: ['whip', 'wipe', 'spin'], face: 'mono',
    pace: 'fast, mechanical, steps-like', easing: 'easeInOutQuart', dominance: 'light, information-dense',
    accent: 'one functional (amber/green for up/down)',
    look: 'minimal, counters and charts ARE the content',
    blurb: 'dense, mechanical, functional. Data and finance. The count easing IS the story',
    antiBlurb: 'dense charts and counters, mechanical and information-first',
  },
  duolingo: {
    cuts: ['wipe', 'iris'], stings: ['confetti', 'sdfIris'], bounceOk: true, restraint: 'low',
    banCuts: [], face: 'sans',
    pace: 'bouncy, overshoot everywhere', easing: 'easeOutBack', dominance: 'light, saturated, rounded',
    accent: 'several bright ones allowed', look: 'confetti on wins',
    blurb: 'playful, bright, rounded. A consumer app. THE one profile where bounce is correct',
    antiBlurb: 'bouncy, confetti, consumer-app cheer',
  },
  vercel: {
    cuts: ['none'], stings: ['glitch', 'chromaticSplit'], bounceOk: false, restraint: 'high',
    banCuts: ['whip', 'wipe', 'spin', 'cube', 'roll'], banMotion: ['bounce'], face: 'sans',
    pace: 'snappy but spare', easing: 'easeOutQuart', dominance: 'pure black',
    accent: 'one white, one accent', look: 'none, no backdrop, maximum contrast',
    blurb: 'keynote restraint, black, sharp. A developer keynote. Maximum restraint',
    antiBlurb: 'pure black, hard cuts only, one dramatic glitch and nothing else',
  },
};

export const PROFILE_NAMES = Object.keys(PROFILES);
