// harness/author/treatment.mjs: WHY THIS FILM LOOKS LIKE THIS, written down while the answer is known.
//
// Stage 4 of the studio pipeline, and the one this repo had no version of. Rationale existed at two
// scales and neither was the film: `assets/brands/<brand>/house-style.md` is the BRAND's read, and a
// scene's `authoring._why` justifies a gate waiver. Nothing recorded the argument for the film itself.
//
// WHY IT HAS TO BE WRITTEN NOW. A treatment's real content is not what was chosen, it is what was
// TURNED DOWN and on what grounds. That information exists for exactly one moment, while the concept
// set is still on the table, and is gone a week later, when all anybody remembers is the film they
// made. harness/author/concept.mjs records the rejected directions with their arguments into a receipt
// for precisely this reason, and this stage reads it back.
//
// THE SPLIT, mirroring scripts/brand/house-style.mjs because it works: a MEASURED block that is
// regenerated from the storyboard, the theme and the concept receipt, and JUDGMENT slots that a tool
// has no business filling. Regenerating never touches what you wrote. What a machine can count, it
// counts; what needs an opinion is marked `<…>` and left alone.
//
//   node harness/author/treatment.mjs <STORYBOARD.md> [--theme <name>]
//   make treatment SB=<storyboard.md>
import fs from 'node:fs';
import path from 'node:path';
import { parseStoryboard } from './storyboard-parse.mjs';
import { readReceipt, writeReceipt } from '../lib/receipt.mjs';
import { expandThemeFile } from '../lib/theme-load.mjs';

const args = process.argv.slice(2);
const SB = args.find((a) => !a.startsWith('--'));
const flag = (n, d) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : d; };
if (!SB || !fs.existsSync(SB)) { console.error('usage: treatment <STORYBOARD.md> [--theme <name>]'); process.exit(2); }

const sb = parseStoryboard(fs.readFileSync(SB, 'utf8'));
if (!sb.beats.length) { console.error(`✗ no beats in ${SB}`); process.exit(1); }
const NAME = path.basename(SB).replace(/\.storyboard\.md$/i, '').replace(/\.md$/i, '');
const OUT = path.join(path.dirname(SB), `${NAME}.treatment.md`);
const strip = (s) => String(s || '').replace(/\s+/g, ' ').trim();

// ── what the machine can count ─────────────────────────────────────────────────────────────────────
const spans = sb.beats.map((b) => b.duration ?? (b.end != null && b.start != null ? b.end - b.start : null)).filter((n) => n != null);
const median = spans.length ? [...spans].sort((a, b) => a - b)[spans.length >> 1] : null;
const DUR = sb.duration || spans.reduce((a, b) => a + b, 0);

const chosen = readReceipt('concept', SB);
const picked = chosen.exists ? chosen.receipt : null;

const themeName = flag('--theme', picked?.preset || sb.theme || 'vawe');
let theme = null;
for (const p of [`themes/${themeName}.json`, `directions/${themeName}.json`]) {
  try { theme = expandThemeFile(JSON.parse(fs.readFileSync(p, 'utf8'))); break; } catch { /* try the next */ }
}
const C = theme?.colors || theme?.base || {};
const F = theme?.fonts || theme?.type || {};

// Pictures vs claims: the show-don't-tell question, asked of the PLAN rather than the render, where it
// is still free to answer. A beat naming no picture is a beat currently planned as pure type.
const noPicture = sb.beats.filter((b) => !strip(b.picture)).length;

const measured = [
  `<!-- MEASURED:START (regenerated by harness/author/treatment.mjs, safe to overwrite, your prose is not touched) -->`,
  `- **Message:** ${sb.message || '(none stated in the storyboard)'}`,
  `- **Audience:** ${sb.audience || '(none stated)'}`,
  `- **Shape:** ${sb.beats.length} beats over ${DUR}s · median beat ${median != null ? `${median.toFixed(2)}s` : '?'}`,
  `- **Thread:** ${sb.thread || picked?.thread || '(not stated, see engine-doctrine/CRAFT/CONTINUITY-WITHOUT-AN-OBJECT.md)'}`,
  `- **Look:** ${themeName}${theme?.dominance ? ` (${theme.dominance})` : ''}${C.bg ? ` · bg \`${C.bg}\`` : ''}${C.accent ? ` · accent \`${C.accent}\`` : ''}`,
  `- **Faces:** sans \`${F.sans || '?'}\` · mono \`${F.mono || '?'}\``,
  `- **Pictures:** ${sb.beats.length - noPicture}/${sb.beats.length} beats name one${noPicture ? `, ${noPicture} currently planned as type only` : ''}`,
  `<!-- MEASURED:END -->`,
].join('\n');

// ── the road not taken, straight from the concept receipt ──────────────────────────────────────────
const rejected = (picked?.rejected || []).map((r) =>
  `- **${r.slug}** (${r.thread}, ${r.preset}), ${r.why}\n  - Why not: <…>`).join('\n');

const body = `# Treatment · ${NAME}

${measured}

## The film in one line

<one sentence a stranger could repeat back. Not the message, the FILM.>

## Why this direction

${picked ? `Chosen: **${picked.picked}**, ${picked.thread}, ${picked.preset}.\n\n${picked.why}\n` : `<no concept receipt found: this treatment cannot say what was rejected, because nothing recorded it.\n Run \`make concept SB=${SB}\` and \`make concept-pick\` first if you want that argument on the record.>\n`}
<Why that beats the alternatives below, in your words. This is the paragraph the treatment exists for.>

${rejected ? `## What was turned down\n\n${rejected}\n` : ''}
## The reference being answered

<what this is measured against, and on which axis. Pace, palette, prop weight, type. "None" is a
 legitimate answer, but say it deliberately rather than leaving the slot empty.>

## The one risk

<the thing most likely to make this film not work, named before it does. If you cannot name one, the
 direction is probably not committed enough to be worth a treatment.>

## What it must not become

<the failure mode to steer away from: the generic version of this film. See engine-doctrine/CRAFT/TASTE-RULES.md.>
`;

// ── regenerate without destroying prose ────────────────────────────────────────────────────────────
// Only the MEASURED block is replaced on a rerun. A tool that overwrites what a human wrote is one they
// run once and then avoid, which is how a rationale document goes stale and starts lying.
let written = 'created';
if (fs.existsSync(OUT)) {
  const src = fs.readFileSync(OUT, 'utf8');
  const s = src.indexOf('<!-- MEASURED:START');
  const e = src.indexOf('<!-- MEASURED:END -->');
  if (s >= 0 && e >= 0) {
    fs.writeFileSync(OUT, src.slice(0, s) + measured + src.slice(e + '<!-- MEASURED:END -->'.length));
    written = 'measured block refreshed, your prose untouched';
  } else {
    fs.writeFileSync(`${OUT}.prev`, src);
    fs.writeFileSync(OUT, body);
    written = `rewritten (no MEASURED markers found; previous kept at ${path.basename(OUT)}.prev)`;
  }
} else {
  fs.writeFileSync(OUT, body);
}

writeReceipt('treatment', SB, { treatment: OUT, theme: themeName });

const open = (fs.readFileSync(OUT, 'utf8').match(/<[^>]{12,}>/g) || []).length;
console.log(`\n  TREATMENT · ${path.basename(SB)} → ${OUT}  (${written})`);
console.log(`  ${sb.beats.length} beats · ${DUR}s · median ${median != null ? median.toFixed(2) + 's' : '?'} · look ${themeName}`);
if (!picked) console.log(`  ~ no concept receipt: the "what was turned down" section is empty, which is the section that matters.`);
console.log(`  ${open} judgment slot(s) still open: a treatment full of <…> is a form, not an argument.\n`);
