// scripts/author/build-orbit.mjs — generate formats/scene/orbit-proof.json.
//
// The single shot that proved keyed depth was worth building. In the reference a ribbon sweeps around
// a photograph, passing IN FRONT of it on the near side and BEHIND it on the far side, so the flat
// composite reads as an object in space. `track` was a static number, so before this the ribbon could
// only ever be entirely in front or entirely behind, and the shot had no way to exist.
//
// Two ribbon halves rather than one, because that is what the real object is: a ring, and a ring is
// near for half its circumference and far for the other half. Each half carries its own depth key.
import fs from 'node:fs';

const OUT = 'formats/scene/orbit-proof.json';
const DUR = 4.0;
const CX = 960, CY = 540;             // 16:9 centre
const PW = 620, PH = 400;             // the photograph, the thing being orbited

// The photo sits at depth 5. A half-ring keyed from 9 down to 1 crosses it exactly once, and the
// crossing is what sells the space — not the sweep, the OCCLUSION.
const layers = [
  {
    type: 'image', id: 'photo', src: '/assets/brands/zerochrome/photos/architecture-interior-landscape-2.jpg',
    x: CX - PW / 2, y: CY - PH / 2, w: PW, h: PH, radius: 14, track: 5,
    start: 0, duration: DUR, anim: 'fade', enterDur: 0.5, exitDur: 0,
  },
];

// the two halves of the ring, each a rotating arc drawn as an SVG stroke
const arc = (id, d, color, track0, track1) => ({
  type: 'svg', id, d, viewBox: '0 0 900 900',
  fill: 'none', stroke: color, strokeWidth: 30,
  x: CX - 450, y: CY - 450, w: 900, h: 900, track: track0,
  start: 0, duration: DUR, anim: 'none', exitDur: 0,
  motion: [
    { t: 0, rot: 0, track: track0 },
    { t: DUR, rot: 360, track: track1, ease: 'linear' },
  ],
});

// The two halves of one ring. Near half starts in front of the photo (9) and ends behind it (1); far
// half is the mirror. As they rotate, each crosses the photo's depth of 5 exactly once.
layers.push(arc('ribbonA', 'M 150 450 A 300 300 0 0 1 750 450', '#c8e64a', 9, 1));
layers.push(arc('ribbonB', 'M 750 450 A 300 300 0 0 1 150 450', '#0f5132', 1, 9));

const scene = {
  module: 'scene',
  theme: 'default',
  aspect: '16:9',
  duration: DUR,
  authoringNote: 'Generated by scripts/author/build-orbit.mjs. Proof scene for KEYED DEPTH (`track` in a '
    + 'motion key): a ribbon that passes in front of a photograph on the near side of its arc and behind '
    + 'it on the far side. Not a deliverable, a primitive test.',
  authoring: {
    allow: ['no-camera', 'plain-slideshow', 'no-visual-vocabulary', 'no-continuous-object-inferred'],
    _why: {
      'no-camera': 'A primitive test holds a locked frame so the only thing moving is the thing under test.',
      'plain-slideshow': 'The ambition floor counts presets and cuts. This has one continuous move and no cuts by design.',
      'no-visual-vocabulary': 'One photograph and one ribbon; there is nothing here to explain, the film IS the mechanism.',
      'no-continuous-object-inferred': 'Every layer is on screen for the whole four seconds; there is no junction to carry an object across.',
    },
  },
  layers,
  bg: [{ t: 0, preset: 'plain', from: 0, to: DUR }],
  audio: { silent: true },
};

fs.writeFileSync(OUT, JSON.stringify(scene, null, 2) + '\n');
console.log(`✓ ${OUT}  ${layers.length} layers · ${DUR}s`);
console.log('  photo at depth 5; ribbon halves cross it in opposite directions (9→1 and 1→9).');
