// scripts/author/concept.mjs — N DIRECTIONS FOR ONE BRIEF, before any of them is built.
//
// The missing first stage. Every other stage here refines a single idea; nothing ever produced a
// second one. That absence has a visible symptom: an anti-sameness LEDGER had to be invented to catch
// films repeating each other after the fact. A backstop catching a symptom is evidence of a missing
// stage, and this is the stage.
//
// It is also why `scripts/gates/compare.mjs` existed as a comparator with nothing feeding it: the
// selection tool was built before the thing that produces something to select between.
//
// WHAT AN OPTION IS. Not a palette swap. A direction commits to three decisions at once, and they are
// the three that actually change a film:
//   THREAD  what survives a cut (docs/CRAFT/CONTINUITY-WITHOUT-AN-OBJECT.md) — an object that
//           transforms, a sentence that never finishes, a match cut, a travelling camera, a counter.
//   PACE    the median beat length, which sets beat COUNT for a fixed duration. The reference study
//           put a good film at a 1.52s median against our habitual 2.5-4s; pace is not a detail.
//   LOOK    one of the seven design systems in presets/, mapped onto the brand's own colours by
//           scripts/brand/theme-remix.mjs.
//
// WHY THE DIVERGENCE IS MEASURED, NOT ASSERTED. Three options generated by one process tend to be one
// option with three palettes, and nobody notices because they are compared side by side where small
// differences look large. scripts/gates/similarity.mjs already scores two designs on separate axes
// (vocabulary, skeleton, layout, colour) and already defines the bar it treats as too close: >0.55 is
// CLOSE, >0.75 is SAME. So the set is scored pairwise and the stage FAILS if any pair lands above
// 0.55, naming the two options and the axis they collapsed on. An option set that cannot pass its own
// distinctness check is not a set of options.
//
//   node scripts/author/concept.mjs <STORYBOARD.md> [--n 3] [--strict]
//   make concept SB=<storyboard.md> [N=3]
// then: make compare ARGS="…"   ·   make concept-pick SB=… OPTION=<slug>
import fs from 'node:fs';
import path from 'node:path';
import { parseStoryboard } from './storyboard-parse.mjs';
import { writeReceipt } from '../lib/receipt.mjs';

const args = process.argv.slice(2);
const SB = args.find((a) => !a.startsWith('--'));
const flag = (n, d) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : d; };
const STRICT = args.includes('--strict');
const N = Math.max(2, Math.min(7, +flag('--n', 3) || 3));
if (!SB || !fs.existsSync(SB)) {
  console.error('usage: concept <STORYBOARD.md> [--n 3] [--strict]');
  process.exit(2);
}

const OUTDIR = 'formats/scene/_concepts';
const CLOSE = 0.55;                 // similarity.mjs's own "too close" line; not a new number

// ── the directions ─────────────────────────────────────────────────────────────────────────────────
// Ordered so that taking the first N gives the widest spread available: thread, pace band and preset
// dominance all change between adjacent entries, so `--n 2` is already a real choice rather than two
// neighbours. Each `why` is the argument FOR that direction, and it is what the treatment stage later
// records as the road not taken.
const DIRECTIONS = [
  { slug: 'held-object', thread: 'transforming object', pace: 3.4, preset: 'editorial',
    why: 'One prop carries the whole film and changes shape at each junction. Slow enough to read, and the most legible option: the viewer always knows what they are looking at.' },
  { slug: 'fast-sentence', thread: 'unfinished sentence', pace: 1.4, preset: 'technical',
    why: 'One sentence, a clause per shot, none of them finishing. Buys total visual freedom (every beat can be a new world) at a cut rate that leaves no room for a slow entrance.' },
  { slug: 'travelled', thread: 'camera travel', pace: 2.2, preset: 'bold',
    why: 'One continuous space the camera moves through, so the cuts are positions rather than subjects. Needs the beats to share a world, which constrains the props.' },
  { slug: 'counted', thread: 'counter or progress', pace: 2.0, preset: 'mono',
    why: 'A number or a list accumulates across every cut. The cheapest continuity to hold and the easiest to make feel mechanical; it lives or dies on what the number means.' },
  { slug: 'rhymed', thread: 'match cut', pace: 1.8, preset: 'warm',
    why: 'Each cut rhymes on a shape or a direction of travel. The most cinematic option and the most brittle: two frames that do not actually rhyme read as a mistake.' },
  { slug: 'asked', thread: 'open question', pace: 2.6, preset: 'glass',
    why: 'An unanswered question holds the film open and the payoff closes it. Strongest hook of the set, and it fails hardest if the ending does not genuinely answer.' },
  { slug: 'pulsed', thread: 'rhythm', pace: 1.2, preset: 'mesh',
    why: 'Cuts land on a fixed pulse and the content fits the grid. Reads as confident and edited; demands the most material, because a fast grid eats beats.' },
];

// ── pick: promote one direction and RECORD THE ONES TURNED DOWN ────────────────────────────────────
// The rejected set is the point, not bookkeeping. A treatment's real content is why this direction and
// not the others, and that argument is only available at the moment of choosing — a week later nobody
// remembers what was on the table. scripts/author/treatment.mjs reads this receipt.
const PICK = flag('--pick', null);
if (PICK) {
  const src = path.join(OUTDIR, `${path.basename(SB).replace(/\.storyboard\.md$/i, '').replace(/\.md$/i, '')}-${PICK}.storyboard.md`);
  if (!fs.existsSync(src)) {
    console.error(`✗ no such direction: ${src}\n  run \`make concept SB=${SB}\` first, or check the slug.`);
    process.exit(2);
  }
  const dir = DIRECTIONS.find((d) => d.slug === PICK);
  // The target is overwritten, so the previous version is kept beside it rather than lost. A stage that
  // destroys the thing it replaces is not a stage anybody will run twice.
  if (fs.existsSync(SB)) {
    fs.copyFileSync(SB, `${SB}.prev`);
    console.log(`  previous storyboard kept at ${SB}.prev`);
  }
  fs.copyFileSync(src, SB);
  writeReceipt('concept', SB, {
    picked: PICK, thread: dir?.thread, preset: dir?.preset, why: dir?.why,
    rejected: DIRECTIONS.filter((d) => d.slug !== PICK).map((d) => ({ slug: d.slug, thread: d.thread, preset: d.preset, why: d.why })),
  });
  console.log(`  ✓ ${PICK} promoted → ${SB}`);
  console.log(`    thread ${dir?.thread} · look ${dir?.preset}`);
  console.log(`\n  next: make treatment SB=${SB}   (it reads which directions you turned down)\n`);
  process.exit(0);
}

const sb = parseStoryboard(fs.readFileSync(SB, 'utf8'));
if (!sb.beats.length) { console.error(`✗ no beats in ${SB}`); process.exit(1); }
const DUR = sb.duration || sb.beats.reduce((a, b) => a + (b.duration || 3), 0) || 15;
const NAME = path.basename(SB).replace(/\.storyboard\.md$/i, '').replace(/\.md$/i, '');
const strip = (s) => String(s || '').replace(/\s+/g, ' ').trim();

// ── redistribute the brief's content across a different beat count ─────────────────────────────────
// Content is NEVER invented. Fewer beats merge adjacent copy; more beats leave an explicit placeholder
// the author has to answer, in the same spirit as the `<…>` slots scripts/brand/house-style.mjs emits.
// A tool that silently writes filler copy produces N films that are all subtly wrong in the same way.
function redistribute(beats, target) {
  if (target === beats.length) return beats.map((b) => ({ ...b, _new: false }));
  const out = [];
  if (target < beats.length) {
    const per = beats.length / target;
    for (let i = 0; i < target; i++) {
      const group = beats.slice(Math.round(i * per), Math.max(Math.round((i + 1) * per), Math.round(i * per) + 1));
      out.push({
        name: group[0].name,
        onscreen: group.flatMap((g) => g.onscreen || []),
        narration: group.map((g) => strip(g.narration)).filter(Boolean).join(' '),
        picture: group[0].picture, why: group[0].why, _new: false,
        _merged: group.length > 1 ? group.length : 0,
      });
    }
    return out;
  }
  for (let i = 0; i < target; i++) {
    const src = beats[Math.floor((i * beats.length) / target)];
    const first = Math.floor(((i - 1) * beats.length) / target) !== Math.floor((i * beats.length) / target);
    out.push(first || i === 0
      ? { ...src, _new: false }
      : { name: `${src.name} (continued)`, onscreen: [], narration: '', picture: '', why: '', _new: true });
  }
  return out;
}

// THE BEAT ARC FOLLOWS THE THREAD. This used to be one fixed cycle for every direction, which made the
// beat-type skeleton nearly identical across directions and collapsed the distinctness score on the
// `skeleton` axis — the generator's fault, not the check's. It is also just wrong: a counter film really
// does accumulate proof beats, a question film really does hold its hook open, a match-cut film really
// does alternate. The middle of each arc repeats to fill whatever beat count the pace implies; the first
// and last beat are always the hook and the payoff.
const ARCS = {
  'transforming object': ['build', 'build', 'proof'],
  'unfinished sentence': ['build', 'problem', 'build', 'proof'],
  'camera travel': ['build', 'proof', 'build'],
  'counter or progress': ['proof', 'proof', 'build'],
  'match cut': ['build', 'proof'],
  'open question': ['problem', 'build', 'problem', 'proof'],
  rhythm: ['proof', 'build', 'proof', 'problem'],
};
const typeAt = (i, n, thread) => {
  if (i === 0) return 'hook';
  if (i === n - 1) return 'payoff';
  const arc = ARCS[thread] || ['build', 'problem', 'proof'];
  return arc[(i - 1) % arc.length];
};

function buildOption(dir) {
  const count = Math.max(3, Math.round(DUR / dir.pace));
  const span = +(DUR / count).toFixed(2);
  const beats = redistribute(sb.beats, count);
  const preset = JSON.parse(fs.readFileSync(`presets/${dir.preset}.json`, 'utf8'));

  const lines = [];
  lines.push('---');
  lines.push(`message: ${sb.message || '<the one sentence this film has to land>'}`);
  lines.push(`audience: ${sb.audience || '<who this is for>'}`);
  lines.push(`arc: ${sb.arc || '<the shape, in one line>'}`);
  lines.push(`thread: ${dir.thread}`);
  lines.push(`object: ${dir.thread === 'transforming object' ? (sb.object || '<the prop that carries it>') : `none — the thread is ${dir.thread}`}`);
  lines.push(`duration: ${DUR}s`);
  lines.push(`format: ${sb.format || '1080x1920'}`);
  lines.push(`concept: ${dir.slug} · ${dir.preset} (${preset.dominance})`);
  lines.push('---');
  lines.push('');
  lines.push(`<!-- DIRECTION: ${dir.slug}`);
  lines.push(`     thread ${dir.thread} · ${count} beats at ~${span}s · look ${dir.preset} (${preset.dominance})`);
  lines.push(`     ${dir.why}`);
  lines.push(`     ${preset.desc}`);
  lines.push('     Generated by scripts/author/concept.mjs from ' + path.basename(SB) + '. The STRUCTURE and the');
  lines.push('     LOOK are decisions this direction makes; every <…> is a decision it deliberately leaves');
  lines.push('     to you, because a tool that invents copy produces options that are all wrong alike. -->');
  lines.push('');

  let t = 0;
  beats.forEach((b, i) => {
    const end = +(t + span).toFixed(2);
    const type = typeAt(i, count, dir.thread);
    lines.push(`## Beat ${i + 1}: ${b._new ? '<name this beat>' : strip(b.name).replace(/^Beat \d+:\s*/, '')} (${t}s-${end}s)`);
    lines.push(`- type: ${type}`);
    lines.push(`- object: ${dir.thread === 'transforming object' ? '<what shape the prop is in here>' : `<what carries the ${dir.thread} at this beat>`}`);
    lines.push(`- picture: ${b._new ? '<what this beat SHOWS — not what it says>' : strip(b.picture) || '<what this beat SHOWS>'}`);
    lines.push(`- mechanism: <the motion (make blueprints · docs/EFFECTS.md)>`);
    lines.push(`- becomes: <the X becomes the Y at this junction>`);
    lines.push(`- onscreen: ${(b.onscreen || []).map(strip).filter(Boolean).join(' | ') || '<the words on screen>'}`);
    if (strip(b.narration)) lines.push(`- narration: ${strip(b.narration)}`);
    lines.push(`- why: ${b._new ? '<why this beat earns its seconds>' : strip(b.why) || '<why this beat earns its seconds>'}`);
    lines.push(`- duration: ${span}s`);
    lines.push('');
    t = end;
  });

  return { dir, count, span, preset, md: lines.join('\n') + '\n',
    placeholders: (lines.join('\n').match(/<[^>]+>/g) || []).length };
}

const options = DIRECTIONS.slice(0, N).map(buildOption);

fs.mkdirSync(OUTDIR, { recursive: true });
for (const o of options) {
  fs.writeFileSync(path.join(OUTDIR, `${NAME}-${o.dir.slug}.storyboard.md`), o.md);
}

// ── prove they are different ───────────────────────────────────────────────────────────────────────
// WHAT THIS CHECKS, AND WHAT IT DELIBERATELY DOES NOT.
//
// The first version of this built a fake scene per direction and scored the set with
// scripts/gates/similarity.mjs. Two things were wrong with that, and both were measured rather than
// argued. First, the proxy was FABRICATED: similarity.mjs reads layer vocabulary, beat skeleton, layout
// and colour off a finished scene, and a concept has none of those yet, so the score described the
// sketch I had just invented. It failed a perfectly good set of three on a `layout` axis that came
// entirely from fingerprint() substituting default coordinates. Second, once the fabrication was
// removed the check turned out to be TAUTOLOGICAL: every direction in the table already carries a
// unique thread and a unique preset, so a pairwise comparison can only re-report what the table
// guarantees by construction.
//
// So the honest check is on the table itself — an invariant over real data, which catches the actual
// regression available here: someone adding an eighth direction that duplicates a thread or a look.
// The genuine cross-film sameness check already exists, runs on finished scenes where the data is real,
// and is called `make ledger`.
const dup = (key, label) => {
  const seen = new Map();
  for (const o of options) {
    const k = o.dir[key];
    if (seen.has(k)) return `two directions share the same ${label} ("${k}"): "${seen.get(k)}" and "${o.dir.slug}". A direction is defined by its thread, its pace and its look; duplicate any one and the pair stops being a real alternative.`;
    seen.set(k, o.dir.slug);
  }
  return null;
};
const problems = [dup('thread', 'thread'), dup('preset', 'look')].filter(Boolean);

// Pace is reported, not enforced. Two films can share a cut rate and still be entirely different films
// if the thread and the look differ, so a close pace is information for the author rather than a fault.
const closePace = [];
for (let i = 0; i < options.length; i++) {
  for (let j = i + 1; j < options.length; j++) {
    const r = Math.max(options[i].dir.pace, options[j].dir.pace) / Math.min(options[i].dir.pace, options[j].dir.pace);
    if (r < 1.25) closePace.push(`${options[i].dir.slug} and ${options[j].dir.slug} cut at nearly the same rate (${r.toFixed(2)}x apart)`);
  }
}

console.log(`\n  CONCEPT · ${path.basename(SB)} → ${options.length} directions for a ${DUR}s film`);
console.log(`  message: ${sb.message || '(none stated)'}\n`);
console.log(`  ${'direction'.padEnd(15)} ${'thread'.padEnd(22)} ${'beats'.padEnd(14)} ${'look'.padEnd(11)} open`);
console.log(`  ${'─'.repeat(15)} ${'─'.repeat(22)} ${'─'.repeat(14)} ${'─'.repeat(11)} ────`);
for (const o of options) {
  console.log(`  ${o.dir.slug.padEnd(15)} ${o.dir.thread.padEnd(22)} ${`${o.count} @ ${o.span}s`.padEnd(14)} ${`${o.dir.preset}/${o.preset.dominance}`.padEnd(11)} ${o.placeholders}`);
}
console.log(`\n  ${OUTDIR}/${NAME}-<direction>.storyboard.md  ·  "open" counts the decisions left to you\n`);

for (const p of problems) console.log(`  ✗ [options-collapse] ${p}`);
for (const c of closePace) console.log(`  ~ [close-pace] ${c} — fine if the thread and look carry it, worth changing if they do not.`);
if (problems.length) { console.log(''); process.exit(1); }
console.log('  ✓ every direction commits to a different thread and a different look.\n');
console.log('  These are STARTING POINTS, not finished films: whether the one you pick ends up too close');
console.log('  to something already shipped is a question about a real scene, and `make ledger` answers it.\n');
console.log('  next: fill the <…> slots in the direction you believe in, then');
console.log(`        make concept-pick SB=${SB} OPTION=<direction>\n`);
process.exit(STRICT && options.some((o) => o.placeholders > 40) ? 1 : 0);
