// scripts/media/globe-dots.mjs — bake the world into a list of points, once, offline.
//
//   node scripts/media/globe-dots.mjs [--spacing 2.2] [--src <geojson>] [--out assets/globe/dots.json]
//   make globe-dots
//
// WHY BAKE. The obvious way to put a globe on screen is `three-globe`, which is MIT and good. Measured
// against what we need it costs 493 KB bundled, 24 MB unpacked, and it pulls @tweenjs/tween.js plus six
// d3 packages — and its arc animation is clock-driven, so the first thing we would do is switch off its
// main feature and drive the dash ourselves. What we actually want from it is a list of points on land,
// which is a build-time question with a fixed answer.
//
// So d3-geo runs HERE, once, and ships nothing. The runtime scene is plain THREE.Points over a
// Float32Array (core/three-fx.js), with no library that owns a clock anywhere near the render loop.
// `core/three-fx.js` already draws this line: "anything genuinely stateful does not belong here at all,
// it belongs in the offline baker."
//
// EQUAL AREA, NOT AN EVEN LAT/LON GRID. Stepping longitude by a constant puts the same number of dots
// on the equator as on the 80th parallel, where a degree of longitude is a sixth as wide, so the poles
// pile up into white caps and the tropics look sparse. The ring below scales its longitude step by
// 1/cos(lat), which is the same correction the band axis needed in the shader.
//
// The source is Natural Earth (public domain), committed to the repo rather than fetched at bake time:
// a build that reaches the network is a build that fails on the day the network does.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { geoContains } from 'd3-geo';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const arg = (k, d) => { const i = process.argv.indexOf(`--${k}`); return i > 0 ? process.argv[i + 1] : d; };

const SPACING = Number(arg('spacing', 2.2));          // degrees between dots at the equator
const SRC = arg('src', 'assets/globe/countries.geojson');
const OUT = arg('out', 'core/globe-dots.js');

const srcPath = path.join(ROOT, SRC);
if (!fs.existsSync(srcPath)) {
  console.error(`✗ missing ${SRC}\n  Natural Earth 110m admin-0 countries, public domain:\n`
    + `  curl -sL -o ${SRC} https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson`);
  process.exit(1);
}
const world = JSON.parse(fs.readFileSync(srcPath, 'utf8'));

// One test against the whole collection, not per feature: d3-geo takes a FeatureCollection and this is
// the difference between one pass and 177 of them.
const lonlat = [];
for (let lat = -84; lat <= 84; lat += SPACING) {
  const ring = Math.max(1, Math.round((360 / SPACING) * Math.cos((lat * Math.PI) / 180)));
  for (let i = 0; i < ring; i++) {
    const lon = -180 + (360 * i) / ring;
    if (geoContains(world, [lon, lat])) lonlat.push(+lon.toFixed(3), +lat.toFixed(3));
  }
}

// A JS MODULE, not a JSON asset. The scene builder in core/three-fx.js is synchronous and so is
// pose(), so a fetch would have to be preloaded and threaded through boot for a table of constants
// that never changes. A static import is the honest shape: this IS engine data now, baked, and the
// only thing that regenerates it is this script.
//
// Flat pairs, not objects. It is read straight into a Float32Array and an array of {lon,lat} would
// triple the file for nobody's benefit.
const body = `// GENERATED by scripts/media/globe-dots.mjs (\`make globe-dots\`) — DO NOT EDIT.
//
// ${lonlat.length / 2} points on land, sampled at ${SPACING}° equal-area spacing from Natural Earth
// 110m admin-0 (public domain, committed at assets/globe/countries.geojson).
//
// Flat [lon, lat, lon, lat, …] in degrees. The scene converts to cartesian once at build; nothing here
// is touched per frame.
export const SPACING = ${SPACING};
export const LONLAT = [${lonlat.join(',')}];
`;
fs.mkdirSync(path.dirname(path.join(ROOT, OUT)), { recursive: true });
fs.writeFileSync(path.join(ROOT, OUT), body);
const kb = (fs.statSync(path.join(ROOT, OUT)).size / 1024).toFixed(0);
console.log(`✓ ${OUT} — ${lonlat.length / 2} land points at ${SPACING}° spacing (${kb} KB)`);
